/**
 * The Farm Tales catalog, every entry the 1.0.0 jar ships.
 *
 * GENERATED by scripts/generate-farm-tales-catalog.mjs from the plugin's own
 * catalog/*.yml. Do not edit by hand; rerun the script.
 *
 * 134 entries: 54 vegetables, 50 fruits, 30 meats.
 * 34 of them are in the free Lite edition.
 *
 * growth is base-growth-seconds before the global multiplier, water and
 * fertilizer. form is crop (on farmland), potted (in a flower pot), tree (a
 * fruit tree the plugin builds) or meat. rides is the vanilla item the entry
 * sits on when there is no resource pack.
 */

export const FTCatalog = [
  {
    "id": "lettuce",
    "name": "Lettuce",
    "kind": "vegetable",
    "form": "crop",
    "growth": 360,
    "rides": "Kelp",
    "animal": null,
    "grade": null,
    "nutrition": [
      "Vitamin A 2",
      "Potassium 1"
    ],
    "lite": true,
    "brewing": false
  },
  {
    "id": "spinach",
    "name": "Spinach",
    "kind": "vegetable",
    "form": "crop",
    "growth": 420,
    "rides": "Kelp",
    "animal": null,
    "grade": null,
    "nutrition": [
      "Iron 3",
      "Vitamin A 2"
    ],
    "lite": true,
    "brewing": false
  },
  {
    "id": "kale",
    "name": "Kale",
    "kind": "vegetable",
    "form": "crop",
    "growth": 480,
    "rides": "Kelp",
    "animal": null,
    "grade": null,
    "nutrition": [
      "Vitamin A 3",
      "Calcium 2",
      "Iron 1"
    ],
    "lite": true,
    "brewing": false
  },
  {
    "id": "arugula",
    "name": "Arugula",
    "kind": "vegetable",
    "form": "crop",
    "growth": 390,
    "rides": "Seagrass",
    "animal": null,
    "grade": null,
    "nutrition": [
      "Antioxidant 2",
      "Vitamin A 1"
    ],
    "lite": false,
    "brewing": false
  },
  {
    "id": "bok_choy",
    "name": "Bok Choy",
    "kind": "vegetable",
    "form": "crop",
    "growth": 440,
    "rides": "Fern",
    "animal": null,
    "grade": null,
    "nutrition": [
      "Calcium 2",
      "Vitamin C 2"
    ],
    "lite": false,
    "brewing": false
  },
  {
    "id": "swiss_chard",
    "name": "Swiss Chard",
    "kind": "vegetable",
    "form": "crop",
    "growth": 470,
    "rides": "Fern",
    "animal": null,
    "grade": null,
    "nutrition": [
      "Iron 2",
      "Vitamin A 2"
    ],
    "lite": false,
    "brewing": false
  },
  {
    "id": "collard_greens",
    "name": "Collard Greens",
    "kind": "vegetable",
    "form": "crop",
    "growth": 540,
    "rides": "Kelp",
    "animal": null,
    "grade": null,
    "nutrition": [
      "Calcium 3",
      "Vitamin A 1"
    ],
    "lite": false,
    "brewing": false
  },
  {
    "id": "cabbage",
    "name": "Cabbage",
    "kind": "vegetable",
    "form": "crop",
    "growth": 620,
    "rides": "Lily Pad",
    "animal": null,
    "grade": null,
    "nutrition": [
      "Fiber 3",
      "Vitamin C 2"
    ],
    "lite": true,
    "brewing": false
  },
  {
    "id": "celery",
    "name": "Celery",
    "kind": "vegetable",
    "form": "crop",
    "growth": 520,
    "rides": "Bamboo",
    "animal": null,
    "grade": null,
    "nutrition": [
      "Potassium 3",
      "Calcium 1"
    ],
    "lite": true,
    "brewing": false
  },
  {
    "id": "asparagus",
    "name": "Asparagus",
    "kind": "vegetable",
    "form": "crop",
    "growth": 980,
    "rides": "Bamboo",
    "animal": null,
    "grade": null,
    "nutrition": [
      "Vitamin B 2",
      "Potassium 1",
      "Antioxidant 1"
    ],
    "lite": false,
    "brewing": false
  },
  {
    "id": "rhubarb",
    "name": "Rhubarb",
    "kind": "vegetable",
    "form": "crop",
    "growth": 900,
    "rides": "Sugar Cane",
    "animal": null,
    "grade": null,
    "nutrition": [
      "Calcium 3"
    ],
    "lite": false,
    "brewing": false
  },
  {
    "id": "leek",
    "name": "Leek",
    "kind": "vegetable",
    "form": "crop",
    "growth": 640,
    "rides": "Allium",
    "animal": null,
    "grade": null,
    "nutrition": [
      "Vitamin A 1",
      "Calcium 2"
    ],
    "lite": true,
    "brewing": false
  },
  {
    "id": "garlic",
    "name": "Garlic",
    "kind": "vegetable",
    "form": "crop",
    "growth": 700,
    "rides": "Allium",
    "animal": null,
    "grade": null,
    "nutrition": [
      "Antioxidant 3",
      "Vitamin C 1"
    ],
    "lite": true,
    "brewing": false
  },
  {
    "id": "onion",
    "name": "Onion",
    "kind": "vegetable",
    "form": "crop",
    "growth": 800,
    "rides": "Allium",
    "animal": null,
    "grade": null,
    "nutrition": [
      "Antioxidant 2",
      "Vitamin C 2"
    ],
    "lite": true,
    "brewing": false
  },
  {
    "id": "shallot",
    "name": "Shallot",
    "kind": "vegetable",
    "form": "crop",
    "growth": 760,
    "rides": "Allium",
    "animal": null,
    "grade": null,
    "nutrition": [
      "Antioxidant 2",
      "Vitamin B 1"
    ],
    "lite": false,
    "brewing": false
  },
  {
    "id": "radish",
    "name": "Radish",
    "kind": "vegetable",
    "form": "crop",
    "growth": 600,
    "rides": "Beetroot",
    "animal": null,
    "grade": null,
    "nutrition": [
      "Vitamin C 2",
      "Antioxidant 1"
    ],
    "lite": true,
    "brewing": false
  },
  {
    "id": "turnip",
    "name": "Turnip",
    "kind": "vegetable",
    "form": "crop",
    "growth": 850,
    "rides": "Beetroot",
    "animal": null,
    "grade": null,
    "nutrition": [
      "Calcium 2",
      "Vitamin C 2"
    ],
    "lite": true,
    "brewing": false
  },
  {
    "id": "rutabaga",
    "name": "Rutabaga",
    "kind": "vegetable",
    "form": "crop",
    "growth": 1080,
    "rides": "Beetroot",
    "animal": null,
    "grade": null,
    "nutrition": [
      "Carbohydrate 3",
      "Potassium 2"
    ],
    "lite": false,
    "brewing": false
  },
  {
    "id": "parsnip",
    "name": "Parsnip",
    "kind": "vegetable",
    "form": "crop",
    "growth": 960,
    "rides": "Carrot",
    "animal": null,
    "grade": null,
    "nutrition": [
      "Carbohydrate 3",
      "Potassium 2"
    ],
    "lite": true,
    "brewing": false
  },
  {
    "id": "daikon",
    "name": "Daikon",
    "kind": "vegetable",
    "form": "crop",
    "growth": 920,
    "rides": "Hanging Roots",
    "animal": null,
    "grade": null,
    "nutrition": [
      "Fiber 2",
      "Potassium 1"
    ],
    "lite": false,
    "brewing": false
  },
  {
    "id": "celeriac",
    "name": "Celeriac",
    "kind": "vegetable",
    "form": "crop",
    "growth": 1140,
    "rides": "Potato",
    "animal": null,
    "grade": null,
    "nutrition": [
      "Potassium 2",
      "Vitamin B 1"
    ],
    "lite": false,
    "brewing": false
  },
  {
    "id": "sweet_potato",
    "name": "Sweet Potato",
    "kind": "vegetable",
    "form": "crop",
    "growth": 1200,
    "rides": "Potato",
    "animal": null,
    "grade": null,
    "nutrition": [
      "Carbohydrate 4",
      "Vitamin A 3",
      "Fiber 1"
    ],
    "lite": true,
    "brewing": false
  },
  {
    "id": "yam",
    "name": "Yam",
    "kind": "vegetable",
    "form": "crop",
    "growth": 1320,
    "rides": "Potato",
    "animal": null,
    "grade": null,
    "nutrition": [
      "Carbohydrate 4",
      "Potassium 2"
    ],
    "lite": false,
    "brewing": false
  },
  {
    "id": "taro",
    "name": "Taro",
    "kind": "vegetable",
    "form": "crop",
    "growth": 1440,
    "rides": "Potato",
    "animal": null,
    "grade": null,
    "nutrition": [
      "Carbohydrate 4",
      "Potassium 2"
    ],
    "lite": false,
    "brewing": false
  },
  {
    "id": "cassava",
    "name": "Cassava",
    "kind": "vegetable",
    "form": "crop",
    "growth": 1500,
    "rides": "Potato",
    "animal": null,
    "grade": null,
    "nutrition": [
      "Carbohydrate 5",
      "Fiber 1"
    ],
    "lite": false,
    "brewing": false
  },
  {
    "id": "jicama",
    "name": "Jicama",
    "kind": "vegetable",
    "form": "crop",
    "growth": 1020,
    "rides": "Potato",
    "animal": null,
    "grade": null,
    "nutrition": [
      "Fiber 3",
      "Potassium 1"
    ],
    "lite": false,
    "brewing": false
  },
  {
    "id": "eggplant",
    "name": "Eggplant",
    "kind": "vegetable",
    "form": "crop",
    "growth": 900,
    "rides": "Beetroot",
    "animal": null,
    "grade": null,
    "nutrition": [
      "Fiber 3",
      "Antioxidant 2"
    ],
    "lite": true,
    "brewing": false
  },
  {
    "id": "tomato",
    "name": "Tomato",
    "kind": "vegetable",
    "form": "crop",
    "growth": 1160,
    "rides": "Sweet Berries",
    "animal": null,
    "grade": null,
    "nutrition": [
      "Vitamin C 3",
      "Antioxidant 3",
      "Potassium 1"
    ],
    "lite": true,
    "brewing": false
  },
  {
    "id": "bell_pepper",
    "name": "Bell Pepper",
    "kind": "vegetable",
    "form": "crop",
    "growth": 1080,
    "rides": "Crimson Fungus",
    "animal": null,
    "grade": null,
    "nutrition": [
      "Vitamin C 4",
      "Antioxidant 1"
    ],
    "lite": false,
    "brewing": false
  },
  {
    "id": "chili_pepper",
    "name": "Chili Pepper",
    "kind": "vegetable",
    "form": "crop",
    "growth": 1140,
    "rides": "Nether Wart",
    "animal": null,
    "grade": null,
    "nutrition": [
      "Vitamin C 3",
      "Antioxidant 2"
    ],
    "lite": false,
    "brewing": false
  },
  {
    "id": "cucumber",
    "name": "Cucumber",
    "kind": "vegetable",
    "form": "crop",
    "growth": 840,
    "rides": "Bamboo",
    "animal": null,
    "grade": null,
    "nutrition": [
      "Potassium 2",
      "Calcium 1"
    ],
    "lite": false,
    "brewing": false
  },
  {
    "id": "zucchini",
    "name": "Zucchini",
    "kind": "vegetable",
    "form": "crop",
    "growth": 920,
    "rides": "Bamboo",
    "animal": null,
    "grade": null,
    "nutrition": [
      "Potassium 2",
      "Vitamin A 1",
      "Calcium 1"
    ],
    "lite": false,
    "brewing": false
  },
  {
    "id": "butternut_squash",
    "name": "Butternut Squash",
    "kind": "vegetable",
    "form": "crop",
    "growth": 1560,
    "rides": "Pumpkin",
    "animal": null,
    "grade": null,
    "nutrition": [
      "Carbohydrate 3",
      "Vitamin A 3",
      "Potassium 1"
    ],
    "lite": false,
    "brewing": false
  },
  {
    "id": "okra",
    "name": "Okra",
    "kind": "vegetable",
    "form": "crop",
    "growth": 1080,
    "rides": "Pitcher Pod",
    "animal": null,
    "grade": null,
    "nutrition": [
      "Fiber 3",
      "Calcium 1"
    ],
    "lite": false,
    "brewing": false
  },
  {
    "id": "broccoli",
    "name": "Broccoli",
    "kind": "vegetable",
    "form": "crop",
    "growth": 1100,
    "rides": "Sea Pickle",
    "animal": null,
    "grade": null,
    "nutrition": [
      "Vitamin C 3",
      "Calcium 2",
      "Fiber 1"
    ],
    "lite": false,
    "brewing": false
  },
  {
    "id": "cauliflower",
    "name": "Cauliflower",
    "kind": "vegetable",
    "form": "crop",
    "growth": 1140,
    "rides": "Oxeye Daisy",
    "animal": null,
    "grade": null,
    "nutrition": [
      "Vitamin C 3",
      "Calcium 1"
    ],
    "lite": false,
    "brewing": false
  },
  {
    "id": "artichoke",
    "name": "Artichoke",
    "kind": "vegetable",
    "form": "crop",
    "growth": 1620,
    "rides": "Cactus",
    "animal": null,
    "grade": null,
    "nutrition": [
      "Fiber 3",
      "Antioxidant 2",
      "Calcium 1"
    ],
    "lite": false,
    "brewing": false
  },
  {
    "id": "squash_blossom",
    "name": "Squash Blossom",
    "kind": "vegetable",
    "form": "crop",
    "growth": 760,
    "rides": "Torchflower",
    "animal": null,
    "grade": null,
    "nutrition": [
      "Vitamin A 2",
      "Antioxidant 1"
    ],
    "lite": false,
    "brewing": false
  },
  {
    "id": "sweet_corn",
    "name": "Sweet Corn",
    "kind": "vegetable",
    "form": "crop",
    "growth": 1260,
    "rides": "Wheat",
    "animal": null,
    "grade": null,
    "nutrition": [
      "Carbohydrate 4",
      "Vitamin B 1"
    ],
    "lite": true,
    "brewing": false
  },
  {
    "id": "green_pea",
    "name": "Green Pea",
    "kind": "vegetable",
    "form": "crop",
    "growth": 780,
    "rides": "Melon Seeds",
    "animal": null,
    "grade": null,
    "nutrition": [
      "Protein 2",
      "Fiber 2",
      "Vitamin A 1"
    ],
    "lite": false,
    "brewing": false
  },
  {
    "id": "snap_bean",
    "name": "Snap Bean",
    "kind": "vegetable",
    "form": "crop",
    "growth": 840,
    "rides": "Kelp",
    "animal": null,
    "grade": null,
    "nutrition": [
      "Protein 2",
      "Fiber 2"
    ],
    "lite": false,
    "brewing": false
  },
  {
    "id": "soybean",
    "name": "Soybean",
    "kind": "vegetable",
    "form": "crop",
    "growth": 1200,
    "rides": "Pumpkin Seeds",
    "animal": null,
    "grade": null,
    "nutrition": [
      "Protein 4",
      "Fat 2",
      "Calcium 1"
    ],
    "lite": false,
    "brewing": false
  },
  {
    "id": "chickpea",
    "name": "Chickpea",
    "kind": "vegetable",
    "form": "crop",
    "growth": 1260,
    "rides": "Pumpkin Seeds",
    "animal": null,
    "grade": null,
    "nutrition": [
      "Protein 4",
      "Carbohydrate 2",
      "Fiber 2"
    ],
    "lite": false,
    "brewing": false
  },
  {
    "id": "lentil",
    "name": "Lentil",
    "kind": "vegetable",
    "form": "crop",
    "growth": 1140,
    "rides": "Beetroot Seeds",
    "animal": null,
    "grade": null,
    "nutrition": [
      "Protein 3",
      "Iron 2",
      "Fiber 2"
    ],
    "lite": false,
    "brewing": false
  },
  {
    "id": "black_bean",
    "name": "Black Bean",
    "kind": "vegetable",
    "form": "crop",
    "growth": 1320,
    "rides": "Cocoa Beans",
    "animal": null,
    "grade": null,
    "nutrition": [
      "Protein 3",
      "Fiber 3",
      "Iron 1"
    ],
    "lite": false,
    "brewing": false
  },
  {
    "id": "peanut",
    "name": "Peanut",
    "kind": "vegetable",
    "form": "crop",
    "growth": 1380,
    "rides": "Cocoa Beans",
    "animal": null,
    "grade": null,
    "nutrition": [
      "Protein 3",
      "Fat 3"
    ],
    "lite": false,
    "brewing": false
  },
  {
    "id": "button_mushroom",
    "name": "Button Mushroom",
    "kind": "vegetable",
    "form": "crop",
    "growth": 700,
    "rides": "Brown Mushroom",
    "animal": null,
    "grade": null,
    "nutrition": [
      "Vitamin D 2",
      "Potassium 1"
    ],
    "lite": false,
    "brewing": false
  },
  {
    "id": "shiitake",
    "name": "Shiitake",
    "kind": "vegetable",
    "form": "crop",
    "growth": 1080,
    "rides": "Brown Mushroom",
    "animal": null,
    "grade": null,
    "nutrition": [
      "Vitamin D 3",
      "Vitamin B 1",
      "Iron 1"
    ],
    "lite": false,
    "brewing": false
  },
  {
    "id": "oyster_mushroom",
    "name": "Oyster Mushroom",
    "kind": "vegetable",
    "form": "crop",
    "growth": 940,
    "rides": "Warped Fungus",
    "animal": null,
    "grade": null,
    "nutrition": [
      "Vitamin D 2",
      "Iron 1"
    ],
    "lite": false,
    "brewing": false
  },
  {
    "id": "crimson_truffle",
    "name": "Crimson Truffle",
    "kind": "vegetable",
    "form": "crop",
    "growth": 1800,
    "rides": "Red Mushroom",
    "animal": null,
    "grade": null,
    "nutrition": [
      "Vitamin D 3",
      "Antioxidant 2",
      "Fiber 1"
    ],
    "lite": false,
    "brewing": false
  },
  {
    "id": "barley",
    "name": "Barley",
    "kind": "vegetable",
    "form": "crop",
    "growth": 1080,
    "rides": "Wheat",
    "animal": null,
    "grade": null,
    "nutrition": [
      "Carbohydrate 4",
      "Fiber 2",
      "Vitamin B 1"
    ],
    "lite": false,
    "brewing": true
  },
  {
    "id": "oats",
    "name": "Oats",
    "kind": "vegetable",
    "form": "crop",
    "growth": 960,
    "rides": "Wheat",
    "animal": null,
    "grade": null,
    "nutrition": [
      "Carbohydrate 4",
      "Fiber 3",
      "Protein 1"
    ],
    "lite": false,
    "brewing": true
  },
  {
    "id": "malt",
    "name": "Malt",
    "kind": "vegetable",
    "form": "crop",
    "growth": 1320,
    "rides": "Wheat",
    "animal": null,
    "grade": null,
    "nutrition": [
      "Carbohydrate 5",
      "Vitamin B 2"
    ],
    "lite": false,
    "brewing": true
  },
  {
    "id": "hops",
    "name": "Hops",
    "kind": "vegetable",
    "form": "crop",
    "growth": 1440,
    "rides": "Vine",
    "animal": null,
    "grade": null,
    "nutrition": [
      "Antioxidant 3",
      "Fiber 1"
    ],
    "lite": false,
    "brewing": true
  },
  {
    "id": "strawberry",
    "name": "Strawberry",
    "kind": "fruit",
    "form": "potted",
    "growth": 700,
    "rides": "Sweet Berries",
    "animal": null,
    "grade": null,
    "nutrition": [
      "Vitamin C 3",
      "Antioxidant 2"
    ],
    "lite": true,
    "brewing": false
  },
  {
    "id": "raspberry",
    "name": "Raspberry",
    "kind": "fruit",
    "form": "potted",
    "growth": 740,
    "rides": "Sweet Berries",
    "animal": null,
    "grade": null,
    "nutrition": [
      "Antioxidant 3",
      "Fiber 2"
    ],
    "lite": true,
    "brewing": false
  },
  {
    "id": "blackberry",
    "name": "Blackberry",
    "kind": "fruit",
    "form": "crop",
    "growth": 780,
    "rides": "Sweet Berries",
    "animal": null,
    "grade": null,
    "nutrition": [
      "Antioxidant 3",
      "Fiber 2"
    ],
    "lite": true,
    "brewing": false
  },
  {
    "id": "blueberry",
    "name": "Blueberry",
    "kind": "fruit",
    "form": "potted",
    "growth": 820,
    "rides": "Sweet Berries",
    "animal": null,
    "grade": null,
    "nutrition": [
      "Antioxidant 4",
      "Fiber 1"
    ],
    "lite": true,
    "brewing": false
  },
  {
    "id": "cranberry",
    "name": "Cranberry",
    "kind": "fruit",
    "form": "crop",
    "growth": 880,
    "rides": "Sweet Berries",
    "animal": null,
    "grade": null,
    "nutrition": [
      "Antioxidant 3",
      "Vitamin C 2"
    ],
    "lite": false,
    "brewing": false
  },
  {
    "id": "gooseberry",
    "name": "Gooseberry",
    "kind": "fruit",
    "form": "potted",
    "growth": 760,
    "rides": "Sweet Berries",
    "animal": null,
    "grade": null,
    "nutrition": [
      "Vitamin C 3",
      "Potassium 1"
    ],
    "lite": false,
    "brewing": false
  },
  {
    "id": "redcurrant",
    "name": "Redcurrant",
    "kind": "fruit",
    "form": "potted",
    "growth": 800,
    "rides": "Sweet Berries",
    "animal": null,
    "grade": null,
    "nutrition": [
      "Vitamin C 3",
      "Iron 1"
    ],
    "lite": false,
    "brewing": false
  },
  {
    "id": "boysenberry",
    "name": "Boysenberry",
    "kind": "fruit",
    "form": "crop",
    "growth": 900,
    "rides": "Sweet Berries",
    "animal": null,
    "grade": null,
    "nutrition": [
      "Antioxidant 3",
      "Fiber 2"
    ],
    "lite": false,
    "brewing": false
  },
  {
    "id": "mulberry",
    "name": "Mulberry",
    "kind": "fruit",
    "form": "crop",
    "growth": 960,
    "rides": "Sweet Berries",
    "animal": null,
    "grade": null,
    "nutrition": [
      "Iron 2",
      "Calcium 1",
      "Antioxidant 1"
    ],
    "lite": false,
    "brewing": false
  },
  {
    "id": "elderberry",
    "name": "Elderberry",
    "kind": "fruit",
    "form": "crop",
    "growth": 1020,
    "rides": "Chorus Fruit",
    "animal": null,
    "grade": null,
    "nutrition": [
      "Antioxidant 4",
      "Vitamin A 1"
    ],
    "lite": false,
    "brewing": false
  },
  {
    "id": "cloudberry",
    "name": "Cloudberry",
    "kind": "fruit",
    "form": "potted",
    "growth": 1140,
    "rides": "Honeycomb",
    "animal": null,
    "grade": null,
    "nutrition": [
      "Vitamin C 3",
      "Antioxidant 2"
    ],
    "lite": false,
    "brewing": false
  },
  {
    "id": "moonberry",
    "name": "Moonberry",
    "kind": "fruit",
    "form": "crop",
    "growth": 1500,
    "rides": "Glow Berries",
    "animal": null,
    "grade": null,
    "nutrition": [
      "Antioxidant 4",
      "Potassium 1",
      "Vitamin D 1"
    ],
    "lite": false,
    "brewing": false
  },
  {
    "id": "grape",
    "name": "Grape",
    "kind": "fruit",
    "form": "crop",
    "growth": 1440,
    "rides": "Weeping Vines",
    "animal": null,
    "grade": null,
    "nutrition": [
      "Antioxidant 3",
      "Carbohydrate 1"
    ],
    "lite": true,
    "brewing": false
  },
  {
    "id": "kiwi",
    "name": "Kiwi",
    "kind": "fruit",
    "form": "crop",
    "growth": 1500,
    "rides": "Twisting Vines",
    "animal": null,
    "grade": null,
    "nutrition": [
      "Vitamin C 5",
      "Calcium 1"
    ],
    "lite": false,
    "brewing": false
  },
  {
    "id": "passionfruit",
    "name": "Passionfruit",
    "kind": "fruit",
    "form": "crop",
    "growth": 1740,
    "rides": "Vine",
    "animal": null,
    "grade": null,
    "nutrition": [
      "Vitamin C 3",
      "Fiber 2",
      "Iron 1"
    ],
    "lite": false,
    "brewing": false
  },
  {
    "id": "sea_grape",
    "name": "Sea Grape",
    "kind": "fruit",
    "form": "crop",
    "growth": 1380,
    "rides": "Seagrass",
    "animal": null,
    "grade": null,
    "nutrition": [
      "Iron 2",
      "Calcium 1",
      "Antioxidant 1"
    ],
    "lite": false,
    "brewing": false
  },
  {
    "id": "watermelon",
    "name": "Watermelon",
    "kind": "fruit",
    "form": "crop",
    "growth": 1680,
    "rides": "Melon",
    "animal": null,
    "grade": null,
    "nutrition": [
      "Potassium 3",
      "Vitamin A 1"
    ],
    "lite": true,
    "brewing": false
  },
  {
    "id": "cantaloupe",
    "name": "Cantaloupe",
    "kind": "fruit",
    "form": "crop",
    "growth": 1560,
    "rides": "Melon Slice",
    "animal": null,
    "grade": null,
    "nutrition": [
      "Vitamin A 3",
      "Vitamin C 2"
    ],
    "lite": true,
    "brewing": false
  },
  {
    "id": "honeydew",
    "name": "Honeydew",
    "kind": "fruit",
    "form": "crop",
    "growth": 1620,
    "rides": "Melon Slice",
    "animal": null,
    "grade": null,
    "nutrition": [
      "Vitamin C 2",
      "Potassium 2"
    ],
    "lite": false,
    "brewing": false
  },
  {
    "id": "prickly_pear",
    "name": "Prickly Pear",
    "kind": "fruit",
    "form": "crop",
    "growth": 1560,
    "rides": "Cactus",
    "animal": null,
    "grade": null,
    "nutrition": [
      "Fiber 2",
      "Calcium 2"
    ],
    "lite": false,
    "brewing": false
  },
  {
    "id": "lime",
    "name": "Lime",
    "kind": "fruit",
    "form": "tree",
    "growth": 1620,
    "rides": "Sea Pickle",
    "animal": null,
    "grade": null,
    "nutrition": [
      "Vitamin C 4",
      "Antioxidant 1"
    ],
    "lite": false,
    "brewing": false
  },
  {
    "id": "lemon",
    "name": "Lemon",
    "kind": "fruit",
    "form": "tree",
    "growth": 1680,
    "rides": "Apple",
    "animal": null,
    "grade": null,
    "nutrition": [
      "Vitamin C 5"
    ],
    "lite": true,
    "brewing": false
  },
  {
    "id": "cherry",
    "name": "Cherry",
    "kind": "fruit",
    "form": "tree",
    "growth": 1740,
    "rides": "Sweet Berries",
    "animal": null,
    "grade": null,
    "nutrition": [
      "Antioxidant 3",
      "Potassium 1"
    ],
    "lite": true,
    "brewing": false
  },
  {
    "id": "mandarin",
    "name": "Mandarin",
    "kind": "fruit",
    "form": "tree",
    "growth": 1770,
    "rides": "Apple",
    "animal": null,
    "grade": null,
    "nutrition": [
      "Vitamin C 4",
      "Vitamin A 1"
    ],
    "lite": false,
    "brewing": false
  },
  {
    "id": "plum",
    "name": "Plum",
    "kind": "fruit",
    "form": "tree",
    "growth": 1800,
    "rides": "Apple",
    "animal": null,
    "grade": null,
    "nutrition": [
      "Antioxidant 2",
      "Fiber 2"
    ],
    "lite": true,
    "brewing": false
  },
  {
    "id": "blood_orange",
    "name": "Blood Orange",
    "kind": "fruit",
    "form": "tree",
    "growth": 1830,
    "rides": "Apple",
    "animal": null,
    "grade": null,
    "nutrition": [
      "Vitamin C 5",
      "Antioxidant 3"
    ],
    "lite": true,
    "brewing": false
  },
  {
    "id": "nectarine",
    "name": "Nectarine",
    "kind": "fruit",
    "form": "tree",
    "growth": 1860,
    "rides": "Apple",
    "animal": null,
    "grade": null,
    "nutrition": [
      "Vitamin A 2",
      "Potassium 2"
    ],
    "lite": false,
    "brewing": false
  },
  {
    "id": "peach",
    "name": "Peach",
    "kind": "fruit",
    "form": "tree",
    "growth": 1920,
    "rides": "Apple",
    "animal": null,
    "grade": null,
    "nutrition": [
      "Vitamin A 3",
      "Potassium 1"
    ],
    "lite": true,
    "brewing": false
  },
  {
    "id": "pear",
    "name": "Pear",
    "kind": "fruit",
    "form": "tree",
    "growth": 1980,
    "rides": "Apple",
    "animal": null,
    "grade": null,
    "nutrition": [
      "Fiber 3",
      "Calcium 1"
    ],
    "lite": true,
    "brewing": false
  },
  {
    "id": "fig",
    "name": "Fig",
    "kind": "fruit",
    "form": "tree",
    "growth": 2010,
    "rides": "Cocoa Beans",
    "animal": null,
    "grade": null,
    "nutrition": [
      "Fiber 3",
      "Calcium 2",
      "Carbohydrate 1"
    ],
    "lite": false,
    "brewing": false
  },
  {
    "id": "apricot",
    "name": "Apricot",
    "kind": "fruit",
    "form": "tree",
    "growth": 2040,
    "rides": "Honeycomb",
    "animal": null,
    "grade": null,
    "nutrition": [
      "Vitamin A 3",
      "Potassium 1"
    ],
    "lite": false,
    "brewing": false
  },
  {
    "id": "banana",
    "name": "Banana",
    "kind": "fruit",
    "form": "tree",
    "growth": 2070,
    "rides": "Bamboo",
    "animal": null,
    "grade": null,
    "nutrition": [
      "Carbohydrate 3",
      "Potassium 3",
      "Vitamin B 1"
    ],
    "lite": true,
    "brewing": false
  },
  {
    "id": "grapefruit",
    "name": "Grapefruit",
    "kind": "fruit",
    "form": "tree",
    "growth": 2100,
    "rides": "Shroomlight",
    "animal": null,
    "grade": null,
    "nutrition": [
      "Vitamin C 4",
      "Potassium 2",
      "Vitamin A 1"
    ],
    "lite": false,
    "brewing": false
  },
  {
    "id": "lychee",
    "name": "Lychee",
    "kind": "fruit",
    "form": "tree",
    "growth": 2130,
    "rides": "Popped Chorus Fruit",
    "animal": null,
    "grade": null,
    "nutrition": [
      "Vitamin C 3",
      "Antioxidant 1"
    ],
    "lite": false,
    "brewing": false
  },
  {
    "id": "papaya",
    "name": "Papaya",
    "kind": "fruit",
    "form": "tree",
    "growth": 2160,
    "rides": "Melon Slice",
    "animal": null,
    "grade": null,
    "nutrition": [
      "Vitamin A 3",
      "Vitamin C 3",
      "Calcium 1"
    ],
    "lite": false,
    "brewing": false
  },
  {
    "id": "pawpaw",
    "name": "Pawpaw",
    "kind": "fruit",
    "form": "tree",
    "growth": 2190,
    "rides": "Melon Slice",
    "animal": null,
    "grade": null,
    "nutrition": [
      "Potassium 2",
      "Carbohydrate 2",
      "Vitamin A 1"
    ],
    "lite": false,
    "brewing": false
  },
  {
    "id": "guava",
    "name": "Guava",
    "kind": "fruit",
    "form": "tree",
    "growth": 2220,
    "rides": "Apple",
    "animal": null,
    "grade": null,
    "nutrition": [
      "Vitamin C 5",
      "Fiber 2"
    ],
    "lite": false,
    "brewing": false
  },
  {
    "id": "quince",
    "name": "Quince",
    "kind": "fruit",
    "form": "tree",
    "growth": 2280,
    "rides": "Apple",
    "animal": null,
    "grade": null,
    "nutrition": [
      "Fiber 2",
      "Antioxidant 2"
    ],
    "lite": false,
    "brewing": false
  },
  {
    "id": "starfruit",
    "name": "Starfruit",
    "kind": "fruit",
    "form": "tree",
    "growth": 2310,
    "rides": "Chorus Fruit",
    "animal": null,
    "grade": null,
    "nutrition": [
      "Vitamin C 3",
      "Potassium 1"
    ],
    "lite": false,
    "brewing": false
  },
  {
    "id": "mango",
    "name": "Mango",
    "kind": "fruit",
    "form": "tree",
    "growth": 2340,
    "rides": "Shroomlight",
    "animal": null,
    "grade": null,
    "nutrition": [
      "Vitamin A 3",
      "Vitamin C 3"
    ],
    "lite": true,
    "brewing": false
  },
  {
    "id": "olive",
    "name": "Olive",
    "kind": "fruit",
    "form": "tree",
    "growth": 2370,
    "rides": "Sea Pickle",
    "animal": null,
    "grade": null,
    "nutrition": [
      "Fat 4",
      "Iron 1"
    ],
    "lite": false,
    "brewing": false
  },
  {
    "id": "persimmon",
    "name": "Persimmon",
    "kind": "fruit",
    "form": "tree",
    "growth": 2400,
    "rides": "Apple",
    "animal": null,
    "grade": null,
    "nutrition": [
      "Vitamin A 3",
      "Fiber 2"
    ],
    "lite": false,
    "brewing": false
  },
  {
    "id": "date",
    "name": "Date",
    "kind": "fruit",
    "form": "tree",
    "growth": 2430,
    "rides": "Cocoa Beans",
    "animal": null,
    "grade": null,
    "nutrition": [
      "Carbohydrate 5",
      "Fiber 2",
      "Potassium 1"
    ],
    "lite": false,
    "brewing": false
  },
  {
    "id": "pineapple",
    "name": "Pineapple",
    "kind": "fruit",
    "form": "tree",
    "growth": 2460,
    "rides": "Cactus",
    "animal": null,
    "grade": null,
    "nutrition": [
      "Vitamin C 4",
      "Fiber 2"
    ],
    "lite": false,
    "brewing": false
  },
  {
    "id": "mangrove_plum",
    "name": "Mangrove Plum",
    "kind": "fruit",
    "form": "tree",
    "growth": 2490,
    "rides": "Mangrove Propagule",
    "animal": null,
    "grade": null,
    "nutrition": [
      "Antioxidant 2",
      "Iron 1"
    ],
    "lite": false,
    "brewing": false
  },
  {
    "id": "pomegranate",
    "name": "Pomegranate",
    "kind": "fruit",
    "form": "tree",
    "growth": 2520,
    "rides": "Apple",
    "animal": null,
    "grade": null,
    "nutrition": [
      "Antioxidant 4",
      "Potassium 2"
    ],
    "lite": false,
    "brewing": false
  },
  {
    "id": "avocado",
    "name": "Avocado",
    "kind": "fruit",
    "form": "tree",
    "growth": 2550,
    "rides": "Warped Fungus",
    "animal": null,
    "grade": null,
    "nutrition": [
      "Fat 5",
      "Fiber 3",
      "Potassium 2"
    ],
    "lite": false,
    "brewing": false
  },
  {
    "id": "dragonfruit",
    "name": "Dragonfruit",
    "kind": "fruit",
    "form": "tree",
    "growth": 2580,
    "rides": "Chorus Fruit",
    "animal": null,
    "grade": null,
    "nutrition": [
      "Antioxidant 3",
      "Iron 2"
    ],
    "lite": false,
    "brewing": false
  },
  {
    "id": "coconut",
    "name": "Coconut",
    "kind": "fruit",
    "form": "tree",
    "growth": 2640,
    "rides": "Cocoa Beans",
    "animal": null,
    "grade": null,
    "nutrition": [
      "Fat 4",
      "Fiber 2",
      "Potassium 1"
    ],
    "lite": false,
    "brewing": false
  },
  {
    "id": "jackfruit",
    "name": "Jackfruit",
    "kind": "fruit",
    "form": "tree",
    "growth": 2700,
    "rides": "Pumpkin",
    "animal": null,
    "grade": null,
    "nutrition": [
      "Carbohydrate 3",
      "Fiber 3",
      "Potassium 1"
    ],
    "lite": false,
    "brewing": false
  },
  {
    "id": "spoiled_beef",
    "name": "Spoiled Beef",
    "kind": "meat",
    "form": "meat",
    "growth": null,
    "rides": "Beef",
    "animal": "Cow",
    "grade": "Spoiled",
    "nutrition": [
      "Protein 6",
      "Iron 3",
      "Fat 2"
    ],
    "lite": false,
    "brewing": false
  },
  {
    "id": "tough_beef",
    "name": "Tough Beef",
    "kind": "meat",
    "form": "meat",
    "growth": null,
    "rides": "Beef",
    "animal": "Cow",
    "grade": "Tough",
    "nutrition": [
      "Protein 6",
      "Iron 3",
      "Fat 2"
    ],
    "lite": false,
    "brewing": false
  },
  {
    "id": "common_beef",
    "name": "Common Beef",
    "kind": "meat",
    "form": "meat",
    "growth": null,
    "rides": "Beef",
    "animal": "Cow",
    "grade": "Common",
    "nutrition": [
      "Protein 6",
      "Iron 3",
      "Fat 2"
    ],
    "lite": true,
    "brewing": false
  },
  {
    "id": "good_beef",
    "name": "Good Beef",
    "kind": "meat",
    "form": "meat",
    "growth": null,
    "rides": "Beef",
    "animal": "Cow",
    "grade": "Good",
    "nutrition": [
      "Protein 6",
      "Iron 3",
      "Fat 2"
    ],
    "lite": true,
    "brewing": false
  },
  {
    "id": "prime_beef",
    "name": "Prime Beef",
    "kind": "meat",
    "form": "meat",
    "growth": null,
    "rides": "Beef",
    "animal": "Cow",
    "grade": "Prime",
    "nutrition": [
      "Protein 6",
      "Iron 3",
      "Fat 2"
    ],
    "lite": false,
    "brewing": false
  },
  {
    "id": "exquisite_beef",
    "name": "Exquisite Beef",
    "kind": "meat",
    "form": "meat",
    "growth": null,
    "rides": "Beef",
    "animal": "Cow",
    "grade": "Exquisite",
    "nutrition": [
      "Protein 6",
      "Iron 3",
      "Fat 2"
    ],
    "lite": false,
    "brewing": false
  },
  {
    "id": "spoiled_porkchop",
    "name": "Spoiled Porkchop",
    "kind": "meat",
    "form": "meat",
    "growth": null,
    "rides": "Porkchop",
    "animal": "Pig",
    "grade": "Spoiled",
    "nutrition": [
      "Protein 5",
      "Fat 4",
      "Vitamin B 2"
    ],
    "lite": false,
    "brewing": false
  },
  {
    "id": "tough_porkchop",
    "name": "Tough Porkchop",
    "kind": "meat",
    "form": "meat",
    "growth": null,
    "rides": "Porkchop",
    "animal": "Pig",
    "grade": "Tough",
    "nutrition": [
      "Protein 5",
      "Fat 4",
      "Vitamin B 2"
    ],
    "lite": false,
    "brewing": false
  },
  {
    "id": "common_porkchop",
    "name": "Common Porkchop",
    "kind": "meat",
    "form": "meat",
    "growth": null,
    "rides": "Porkchop",
    "animal": "Pig",
    "grade": "Common",
    "nutrition": [
      "Protein 5",
      "Fat 4",
      "Vitamin B 2"
    ],
    "lite": false,
    "brewing": false
  },
  {
    "id": "good_porkchop",
    "name": "Good Porkchop",
    "kind": "meat",
    "form": "meat",
    "growth": null,
    "rides": "Porkchop",
    "animal": "Pig",
    "grade": "Good",
    "nutrition": [
      "Protein 5",
      "Fat 4",
      "Vitamin B 2"
    ],
    "lite": false,
    "brewing": false
  },
  {
    "id": "prime_porkchop",
    "name": "Prime Porkchop",
    "kind": "meat",
    "form": "meat",
    "growth": null,
    "rides": "Porkchop",
    "animal": "Pig",
    "grade": "Prime",
    "nutrition": [
      "Protein 5",
      "Fat 4",
      "Vitamin B 2"
    ],
    "lite": false,
    "brewing": false
  },
  {
    "id": "exquisite_porkchop",
    "name": "Exquisite Porkchop",
    "kind": "meat",
    "form": "meat",
    "growth": null,
    "rides": "Porkchop",
    "animal": "Pig",
    "grade": "Exquisite",
    "nutrition": [
      "Protein 5",
      "Fat 4",
      "Vitamin B 2"
    ],
    "lite": false,
    "brewing": false
  },
  {
    "id": "spoiled_mutton",
    "name": "Spoiled Mutton",
    "kind": "meat",
    "form": "meat",
    "growth": null,
    "rides": "Mutton",
    "animal": "Sheep",
    "grade": "Spoiled",
    "nutrition": [
      "Protein 5",
      "Fat 3",
      "Iron 2"
    ],
    "lite": false,
    "brewing": false
  },
  {
    "id": "tough_mutton",
    "name": "Tough Mutton",
    "kind": "meat",
    "form": "meat",
    "growth": null,
    "rides": "Mutton",
    "animal": "Sheep",
    "grade": "Tough",
    "nutrition": [
      "Protein 5",
      "Fat 3",
      "Iron 2"
    ],
    "lite": false,
    "brewing": false
  },
  {
    "id": "common_mutton",
    "name": "Common Mutton",
    "kind": "meat",
    "form": "meat",
    "growth": null,
    "rides": "Mutton",
    "animal": "Sheep",
    "grade": "Common",
    "nutrition": [
      "Protein 5",
      "Fat 3",
      "Iron 2"
    ],
    "lite": false,
    "brewing": false
  },
  {
    "id": "good_mutton",
    "name": "Good Mutton",
    "kind": "meat",
    "form": "meat",
    "growth": null,
    "rides": "Mutton",
    "animal": "Sheep",
    "grade": "Good",
    "nutrition": [
      "Protein 5",
      "Fat 3",
      "Iron 2"
    ],
    "lite": false,
    "brewing": false
  },
  {
    "id": "prime_mutton",
    "name": "Prime Mutton",
    "kind": "meat",
    "form": "meat",
    "growth": null,
    "rides": "Mutton",
    "animal": "Sheep",
    "grade": "Prime",
    "nutrition": [
      "Protein 5",
      "Fat 3",
      "Iron 2"
    ],
    "lite": false,
    "brewing": false
  },
  {
    "id": "exquisite_mutton",
    "name": "Exquisite Mutton",
    "kind": "meat",
    "form": "meat",
    "growth": null,
    "rides": "Mutton",
    "animal": "Sheep",
    "grade": "Exquisite",
    "nutrition": [
      "Protein 5",
      "Fat 3",
      "Iron 2"
    ],
    "lite": false,
    "brewing": false
  },
  {
    "id": "spoiled_chicken",
    "name": "Spoiled Chicken",
    "kind": "meat",
    "form": "meat",
    "growth": null,
    "rides": "Chicken",
    "animal": "Chicken",
    "grade": "Spoiled",
    "nutrition": [
      "Protein 6",
      "Vitamin B 2",
      "Vitamin D 1"
    ],
    "lite": false,
    "brewing": false
  },
  {
    "id": "tough_chicken",
    "name": "Tough Chicken",
    "kind": "meat",
    "form": "meat",
    "growth": null,
    "rides": "Chicken",
    "animal": "Chicken",
    "grade": "Tough",
    "nutrition": [
      "Protein 6",
      "Vitamin B 2",
      "Vitamin D 1"
    ],
    "lite": false,
    "brewing": false
  },
  {
    "id": "common_chicken",
    "name": "Common Chicken",
    "kind": "meat",
    "form": "meat",
    "growth": null,
    "rides": "Chicken",
    "animal": "Chicken",
    "grade": "Common",
    "nutrition": [
      "Protein 6",
      "Vitamin B 2",
      "Vitamin D 1"
    ],
    "lite": true,
    "brewing": false
  },
  {
    "id": "good_chicken",
    "name": "Good Chicken",
    "kind": "meat",
    "form": "meat",
    "growth": null,
    "rides": "Chicken",
    "animal": "Chicken",
    "grade": "Good",
    "nutrition": [
      "Protein 6",
      "Vitamin B 2",
      "Vitamin D 1"
    ],
    "lite": true,
    "brewing": false
  },
  {
    "id": "prime_chicken",
    "name": "Prime Chicken",
    "kind": "meat",
    "form": "meat",
    "growth": null,
    "rides": "Chicken",
    "animal": "Chicken",
    "grade": "Prime",
    "nutrition": [
      "Protein 6",
      "Vitamin B 2",
      "Vitamin D 1"
    ],
    "lite": false,
    "brewing": false
  },
  {
    "id": "exquisite_chicken",
    "name": "Exquisite Chicken",
    "kind": "meat",
    "form": "meat",
    "growth": null,
    "rides": "Chicken",
    "animal": "Chicken",
    "grade": "Exquisite",
    "nutrition": [
      "Protein 6",
      "Vitamin B 2",
      "Vitamin D 1"
    ],
    "lite": false,
    "brewing": false
  },
  {
    "id": "spoiled_rabbit",
    "name": "Spoiled Rabbit",
    "kind": "meat",
    "form": "meat",
    "growth": null,
    "rides": "Rabbit",
    "animal": "Rabbit",
    "grade": "Spoiled",
    "nutrition": [
      "Protein 6",
      "Vitamin B 2",
      "Iron 1"
    ],
    "lite": false,
    "brewing": false
  },
  {
    "id": "tough_rabbit",
    "name": "Tough Rabbit",
    "kind": "meat",
    "form": "meat",
    "growth": null,
    "rides": "Rabbit",
    "animal": "Rabbit",
    "grade": "Tough",
    "nutrition": [
      "Protein 6",
      "Vitamin B 2",
      "Iron 1"
    ],
    "lite": false,
    "brewing": false
  },
  {
    "id": "common_rabbit",
    "name": "Common Rabbit",
    "kind": "meat",
    "form": "meat",
    "growth": null,
    "rides": "Rabbit",
    "animal": "Rabbit",
    "grade": "Common",
    "nutrition": [
      "Protein 6",
      "Vitamin B 2",
      "Iron 1"
    ],
    "lite": false,
    "brewing": false
  },
  {
    "id": "good_rabbit",
    "name": "Good Rabbit",
    "kind": "meat",
    "form": "meat",
    "growth": null,
    "rides": "Rabbit",
    "animal": "Rabbit",
    "grade": "Good",
    "nutrition": [
      "Protein 6",
      "Vitamin B 2",
      "Iron 1"
    ],
    "lite": false,
    "brewing": false
  },
  {
    "id": "prime_rabbit",
    "name": "Prime Rabbit",
    "kind": "meat",
    "form": "meat",
    "growth": null,
    "rides": "Rabbit",
    "animal": "Rabbit",
    "grade": "Prime",
    "nutrition": [
      "Protein 6",
      "Vitamin B 2",
      "Iron 1"
    ],
    "lite": false,
    "brewing": false
  },
  {
    "id": "exquisite_rabbit",
    "name": "Exquisite Rabbit",
    "kind": "meat",
    "form": "meat",
    "growth": null,
    "rides": "Rabbit",
    "animal": "Rabbit",
    "grade": "Exquisite",
    "nutrition": [
      "Protein 6",
      "Vitamin B 2",
      "Iron 1"
    ],
    "lite": false,
    "brewing": false
  }
];

export const FTCatalogCounts = {
  "total": 134,
  "vegetables": 54,
  "fruits": 50,
  "meats": 30,
  "lite": 34,
  "trees": 30,
  "potted": 6,
  "brewing": 4
};
