import {
  Currency,
  DamageType,
  EnchantType,
  ResistanceType,
} from "../CE3_Enums";

import spigotImg from "../../../assets/custom_enchants_3/spigot.png";
import wiseImg from "../../../assets/custom_enchants_3/wise.png";
import wisePaymentQr from "../../../assets/custom_enchants_3/wise-payment-qr.png";

export const PluginInformation = {
  title: "Custom Enchantments 3",
  subtitle: "Elevate your server with Epic RPG Gameplay!",
  version: "1.6.0",
  versionReleaseDate: "09/02/2026",
  versionHighlight:
    "The economy release. Kumandra's Economy is supported as an optional soft dependency, so a RACO price can be settled in Kd without RACO ever being minted out of nothing. Plus 25 new enchantments and 15 new treasure items, taking the totals to 159 and 149. Tested on Minecraft 26.2.",
  supportedVersions: "1.16.4 - 26.2",
  treasureCount: 149,
  price: 18.99,
  currency_symbol: "£",
  author: "JayMar921",
  authorSocial: "https://jayharronabejar.vercel.app/",
  tagline: "Turn your server into an RPG, not just a server with extra swords.",
  description:
    "Custom Enchantments 3 is what happens when a plugin stops adding bigger numbers and starts adding things to do. 159 custom enchantments, and most of them are abilities rather than stat bumps. Mine a 3x3 two blocks deep. Fire a bolt that jumps from target to target. Swap places with whatever you are looking at, right in the middle of a fight. Take an enemy's abilities away without touching their health.",
  descriptionMore: [
    "Your players pick a lane and build into it. XP comes from mobs, blocks, crops and quests, every level pays an attribute point, every tenth level pays a passive point, and the cap sits at 200. Spend that first passive point and you commit: Warrior for swords, spears and maces, Archer for the bow, Wizard for the wand and its spells. Changed your mind halfway? The Reset Elixir hands the points back and keeps your level.",
    "Around all of that sits a whole server's worth of systems. 15 shop types you place as real entities that cannot be stolen with a boat. Quests written in chat, no config editing, with 25 already waiting on a fresh install. RACO, a currency with a fixed supply of 1.25 million coins and a price that genuinely moves when your players trade, with its own candlestick chart in game. Loot plots you build yourself that the plugin drops near players and fills with loot, guarded by bandit camps that hit back. 149 treasure items that work from your inventory with nothing to equip.",
    "1.6.0 opens the currency up without giving up standing alone. If you run Kumandra's Economy too, a player can settle a RACO price in Kd and swap between the two in the exchange screen, and the plugin buys that RACO out of the circulating supply rather than minting it, so the supply cap still means what it always meant. If you do not run it, or you switch one setting off, nothing changes at all.",
    "Everything is a config line. Every price, every drop rate, every XP curve, every enchantment. Set a price to 0 and that enchantment stops existing on your server. It runs on Spigot and Paper from 1.16.4 all the way to 26.2, it needs no other plugins, and there is no NMS anywhere in it, so an update to Minecraft does not take the plugin down with it. One payment, updates for life, no subscription.",
  ],
  trialLink:
    "https://www.spigotmc.org/resources/%E2%9C%AF-custom-enchantments-3-1-16-free-%E2%9C%AF.89793/",
  payment: {
    contactEmail: "jaymarplugins@gmail.com",
    paymentSubject: "Custom Enchantments 3 Plugin Payment",
    spigotAccountRequirement:
      "You must have a Spigot account before paying. Your Spigot username is required to receive the plugin.",
    exactPaymentNotice:
      "Pay the exact amount shown. There is no return or refund policy for payments that are less or more than the required amount.",
    paypal: {
      link: "https://www.paypal.com/paypalme/JayMar921",
      discountPercent: 3,
      currencySymbol: "£",
    },
    wise: {
      link: "https://wise.com/pay/me/jayharronmara",
      qr: wisePaymentQr,
      discountPercent: 5,
      currencySymbol: "£",
    },
  },
  supportLink: [
    {
      title: "Buy JayMar a coffee",
      link: "https://buymeacoffee.com/jaymar921",
      icon: "fa-solid fa-mug-hot text-yellow-500",
    },
    {
      title: "PayPal",
      link: "https://www.paypal.com/paypalme/JayMar921",
      icon: "fa-brands fa-paypal text-blue-400",
    },
    {
      title: "Donate via Wise",
      link: "https://wise.com/pay/me/jayharronmara",
      logo: wiseImg,
    },
  ],
  buyLink: [
    {
      title: "Spigot",
      link: "https://www.spigotmc.org/resources/102275/",
      logo: spigotImg,
    },
    {
      title: "PayPal",
      onClick: (setSubcontent) => {
        setSubcontent?.("buy through paypal");
      },
      icon: "fa-brands fa-paypal text-blue-400",
    },
    {
      title: "Wise",
      onClick: (setSubcontent) => {
        setSubcontent?.("buy through wise");
      },
      logo: wiseImg,
    },
  ],
  classes: {
    description:
      "Shape your adventure with three powerful classes: Warrior, Archer, and Mage! Each path unlocks unique skills, buffs, and playstyles, bringing an epic RPG experience to your server. Dominate battles, master magic, or strike from the shadows, the choice is yours!",
    command: "/ce skills",
    class: [
      {
        title: "Warrior",
        icon: "fa-solid fa-shield-halved",
        color: "text-red-500",
        description:
          "Settle in the southern area of the Taiga Biomes. They have the best in attacking ability and endurance, but they're slow in speed and is inaccurate.",
        subdescription: "(You'll be able to use Sword Enchantments)",
        main_attribute: "Strength",
        attributes: [
          "Increase Physical Damage by 0.13",
          "Increase Physical Defense by 0.25",
          "Increase Health Regen by 0.015",
        ],
        skills: [
          {
            title: "SWORD MASTERY",
            description: "Increase sword damage",
          },
          {
            title: "BERSERK",
            description: "Get bonus damage for 0.2 for every hp lost",
          },
          {
            title: "PENETRATION",
            description: "Ignore enemy Damage Resistance by 0.5%",
          },
        ],
      },
      {
        title: "Archer",
        icon: "fa-solid fa-shoe-prints",
        color: "text-green-500",
        description:
          "Inhibit in the northern land of jungle biomes. They shun the use of heavy equipment as it restricts their mobility and agility. They are considered as the quickest and fastest of all the classes.",
        subdescription: "(You'll be able to use Bow Enchantments)",
        main_attribute: "Agility",
        attributes: [
          "Increase Movement Speed by 0.025",
          "Increase Critical Chance by 2%",
          "Increase Physical Damage by 0.125",
        ],
        skills: [
          {
            title: "BOW MASTERY",
            description: "Increase bow damage",
          },
          {
            title: "UNSWERVING SHOT",
            description: "Increase bow range",
          },
          {
            title: "SWIFT ESCAPE",
            description: "Increases Chance to Evade/Ignore Damage",
          },
        ],
      },

      {
        title: "Mage",
        icon: "fa-solid fa-hat-wizard",
        color: "text-blue-500",
        description:
          "Occupies the lands of Snowy Plain. They manifest less physical ability than the other classes but has the strongest magical powers.",
        subdescription: "(You'll be able to use Magic Enchantments)",
        main_attribute: "Intelligence",
        attributes: [
          "Increase Mana Regeneration",
          "Increase Magic Damage",
          "Increase Magic Resistance",
        ],
        skills: [
          {
            title: "WIZARD MASTERY",
            description: "Increase casting range / spell radius by 0.2 blocks",
          },
          {
            title: "HOURGLASS",
            description: "Decrease magic enchantments cooldown",
          },
          {
            title: "MANA CHARGE",
            description: "Increases Mana Regeneration by 0.125",
          },
        ],
      },
    ],
  },
};

export const CommandList = [
  {
    command: "/ce skills",
    description:
      "Open the select Skills UI (on level 10, you can select classes)",
    requireOp: false,
  },
  {
    command: "/ce skills add [player] [amount]",
    description: "Add level to player by amount",
    requireOp: true,
  },
  {
    command: "/ce skills reset [player]",
    description: "Reset player skill level back to 0",
    requireOp: true,
  },
  {
    command: "/ce shop",
    description:
      "Shows the list of shops and it's location within the world. Opens the shop UI if `EnableShopCommand` setting is enabled in config.yml",
    requireOp: false,
  },
  {
    command: "/ce shop add [mobType] [shopType] [shopName]",
    description: "Create a shop at the player's location",
    requireOp: true,
  },
  {
    command: "/ce shop remove [shopName]",
    description: "Remove a shop",
    requireOp: true,
  },
  {
    command: "/ce quest",
    description:
      "Shows the list of quests and it's location within the world. If player is on quest, it shows the active quest details",
    requireOp: false,
  },
  {
    command: "/ce quest add",
    description: "Create a new Quest",
    requireOp: true,
  },
  {
    command: "/ce quest remove",
    description: "Remove an exisiting quest",
    requireOp: true,
  },
  {
    command: "/ce quest list",
    description: "Shows the list of created quests",
    requireOp: true,
  },
  {
    command: "/ce quest modifyEntity",
    description: "Replace the associated quests on a Quest Entity",
    requireOp: true,
  },
  {
    command: "/ce rank",
    description: "Shows the top 10 player rank",
    requireOp: false,
  },
  {
    command: "/ce allies",
    description: "Shows the list of allied players",
    requireOp: false,
  },
  {
    command: "/ce allies add [playerName]",
    description:
      "Add a player into the ally list [Make sure that the player is online]",
    requireOp: false,
  },
  {
    command: "/ce allies remove [playerName]",
    description: "Remove a player from the ally list",
    requireOp: false,
  },
  {
    command: "/ce help",
    description: "Shows the plugin Help UI",
    requireOp: false,
  },
  {
    command: "/ce info",
    description: "Shows the plugin settings information",
    requireOp: false,
  },
  {
    command: "/ce settings",
    description: "Modify plugin settings | may require admin access",
    requireOp: false,
  },
  {
    command: "/ce reload",
    description: "Soft reload plugin",
    requireOp: true,
  },
  {
    command: "/ce ___reset___",
    description: "[TEST COMMAND] Reset yourself back to skill level 0",
    requireOp: true,
  },
  {
    command: "/ce ___test___",
    description: "[TEST COMMAND] Grant max skill level (200)",
    requireOp: true,
  },
  {
    command: "/ce ___lootplot___",
    description: "[TEST COMMAND] Generate a looting plot nearby",
    requireOp: true,
  },
  {
    command: "/ce ___treasure___",
    description: "[TEST COMMAND] Retrieve all Treasure Items",
    requireOp: true,
  },
  {
    command: "/ce ___ceItem___",
    description: "[TEST COMMAND] Retrieve a custom CE Item",
    requireOp: true,
  },
  {
    command: "/ce ___itemData___",
    description: "[TEST COMMAND] Get information about the MainHand item",
    requireOp: true,
  },
];

export const Enchantments = [
  {
    title: "Life Steal",
    type: [EnchantType.SWORD, EnchantType.SPEAR],
    description: "Get a chance to steal your enemies health",
    damageType: [DamageType.PHYSICAL_DMG],
    resistanceType: [ResistanceType.PHYSICAL_RESIST],
    absorbType: [],
    manaCost: 0,
    cooldown: 0,
    maxLevel: 3,
    price: 55,
    currency: Currency.LEVEL,
  },
  {
    title: "Bleed",
    type: [EnchantType.SWORD, EnchantType.SPEAR, EnchantType.MACE],
    description: "Get a chance of bleeding the enemy",
    damageType: [DamageType.PHYSICAL_DMG],
    resistanceType: [ResistanceType.PHYSICAL_RESIST],
    absorbType: [],
    manaCost: 0,
    cooldown: 0,
    maxLevel: 3,
    price: 38,
    currency: Currency.LEVEL,
  },
  {
    title: "Critical",
    type: [EnchantType.SWORD, EnchantType.SPEAR, EnchantType.MACE],
    description: "Deal critical damage to enemy by chance",
    damageType: [DamageType.PHYSICAL_DMG_CRIT],
    resistanceType: [ResistanceType.PHYSICAL_RESIST],
    absorbType: [],
    manaCost: 0,
    cooldown: 0,
    maxLevel: 5,
    price: 85,
    currency: Currency.LEVEL,
  },
  {
    title: "Poison",
    type: [EnchantType.SWORD],
    description: "Apply poison effect to the enemy on hit",
    damageType: [DamageType.PHYSICAL_DMG],
    resistanceType: [ResistanceType.PHYSICAL_RESIST],
    absorbType: [],
    manaCost: 0,
    cooldown: 0,
    maxLevel: 2,
    price: 18,
    currency: Currency.LEVEL,
  },
  {
    title: "Magic Resist",
    type: [EnchantType.CHESTPLATE],
    description: "Reduce Magic Damage taken",
    damageType: [],
    resistanceType: [],
    absorbType: [DamageType.MAGICAL_DMG, DamageType.MAGICAL_PEN],
    manaCost: 0,
    cooldown: 0,
    maxLevel: 5,
    price: 45,
    currency: Currency.LEVEL,
  },
  {
    title: "Mana Steal",
    type: [EnchantType.SWORD],
    description: "Steal mana from your enemy",
    damageType: [],
    resistanceType: [],
    absorbType: [],
    manaCost: 0,
    cooldown: 0,
    maxLevel: 5,
    price: 35,
    currency: Currency.LEVEL,
  },
  {
    title: "Execute",
    type: [EnchantType.SWORD, EnchantType.MACE],
    description: "Deal more damage when your enemy is on low health",
    damageType: [DamageType.PHYSICAL_DMG],
    resistanceType: [ResistanceType.PHYSICAL_RESIST],
    absorbType: [],
    manaCost: 0,
    cooldown: 0,
    maxLevel: 5,
    price: 75,
    currency: Currency.LEVEL,
  },
  {
    title: "LIGHT SPIRIT",
    type: [EnchantType.SWORD],
    description: "Call of lightning! Deal huge magic damage to your enemy",
    damageType: [
      DamageType.PHYSICAL_DMG,
      DamageType.MAGICAL_DMG,
      DamageType.MAGICAL_PEN,
    ],
    resistanceType: [
      ResistanceType.PHYSICAL_RESIST,
      ResistanceType.MAGICAL_RESIST,
    ],
    absorbType: [],
    manaCost: 0,
    cooldown: 0,
    maxLevel: 5,
    price: 55,
    currency: Currency.LEVEL,
  },
  {
    title: "SOUL EATER",
    type: [EnchantType.SWORD, EnchantType.SPEAR],
    description: "Capture your enemy's soul! Slowly stack your sword damage",
    damageType: [DamageType.PHYSICAL_DMG],
    resistanceType: [ResistanceType.PHYSICAL_RESIST],
    absorbType: [],
    manaCost: 0,
    cooldown: 0,
    maxLevel: 5000,
    price: 150,
    currency: Currency.LEVEL,
  },
  {
    title: "WIND STRIKE",
    type: [EnchantType.SWORD, EnchantType.SPEAR],
    description: "Dashes to enemy",
    damageType: [DamageType.MAGICAL_DMG],
    resistanceType: [ResistanceType.MAGICAL_RESIST],
    absorbType: [],
    manaCost: 0,
    cooldown: 0,
    maxLevel: 3,
    price: 40,
    currency: Currency.LEVEL,
  },
  {
    title: "SUDDEN BLOW",
    type: [EnchantType.TRIDENT],
    description: "Has chance to blind and stun the enemy",
    damageType: [DamageType.PHYSICAL_DMG],
    resistanceType: [ResistanceType.PHYSICAL_RESIST],
    absorbType: [],
    manaCost: 0,
    cooldown: 0,
    maxLevel: 4,
    price: 35,
    currency: Currency.LEVEL,
  },
  {
    title: "FALLING STAR",
    type: [EnchantType.MAGIC_WAND],
    description: "Call down a rain of falling stars over the area",
    damageType: [DamageType.MAGICAL_DMG],
    resistanceType: [ResistanceType.MAGICAL_RESIST],
    absorbType: [],
    manaCost: 20.8,
    cooldown: 340,
    maxLevel: 5,
    price: 850,
    currency: Currency.RACO,
  },
  {
    title: "HAIL STORM",
    type: [EnchantType.TRIDENT],
    description: "Cast a hail storm in the area",
    damageType: [DamageType.MAGICAL_DMG],
    resistanceType: [ResistanceType.MAGICAL_RESIST],
    absorbType: [],
    manaCost: 20,
    cooldown: 200,
    maxLevel: 3,
    price: 95,
    currency: Currency.LEVEL,
  },
  {
    title: "TANK",
    type: [EnchantType.ARMORS],
    description: "Gain physical damage resistance",
    damageType: [],
    resistanceType: [],
    absorbType: [DamageType.PHYSICAL_DMG, DamageType.PHYSICAL_DMG_CRIT],
    manaCost: 0,
    cooldown: 0,
    maxLevel: 5,
    price: 45,
    currency: Currency.LEVEL,
  },
  {
    title: "REGAIN",
    type: [EnchantType.CHESTPLATE],
    description: "Get a second life!",
    damageType: [],
    resistanceType: [],
    absorbType: [
      DamageType.PHYSICAL_DMG,
      DamageType.PHYSICAL_DMG_CRIT,
      DamageType.MAGICAL_DMG,
      DamageType.MAGICAL_PEN,
    ],
    manaCost: 0,
    cooldown: 200,
    maxLevel: 5,
    price: 70,
    currency: Currency.LEVEL,
  },
  {
    title: "POISONOUS THORNS",
    type: [EnchantType.CHESTPLATE],
    description: "Get a chance to poison the attacker",
    damageType: [],
    resistanceType: [],
    absorbType: [],
    manaCost: 0,
    cooldown: 0,
    maxLevel: 10,
    price: 33,
    currency: Currency.LEVEL,
  },
  {
    title: "FREEZE",
    type: [EnchantType.LEGGINGS],
    description: "Get a chance to freeze your attacker",
    damageType: [],
    resistanceType: [],
    absorbType: [],
    manaCost: 0,
    cooldown: 0,
    maxLevel: 10,
    price: 47,
    currency: Currency.LEVEL,
  },
  {
    title: "OMNIVAMP",
    type: [EnchantType.CHESTPLATE],
    description: "Get a chance to heal when attacked",
    damageType: [],
    resistanceType: [],
    absorbType: [],
    manaCost: 0,
    cooldown: 0,
    maxLevel: 5,
    price: 52,
    currency: Currency.LEVEL,
  },
  {
    title: "BLINDNESS",
    type: [EnchantType.HELMET],
    description: "When attacked, blind the enemy by chance",
    damageType: [],
    resistanceType: [],
    absorbType: [],
    manaCost: 0,
    cooldown: 0,
    maxLevel: 1,
    price: 20,
    currency: Currency.LEVEL,
  },
  {
    title: "DOUBLE JUMP",
    type: [EnchantType.BOOTS],
    description: "Sneak while on air to jump",
    damageType: [],
    resistanceType: [],
    absorbType: [],
    manaCost: 3,
    cooldown: 0,
    maxLevel: 1,
    price: 25,
    currency: Currency.LEVEL,
  },
  {
    title: "AUTO FARM",
    type: [EnchantType.HOE],
    description: "Get a chance to replant harvested crops",
    damageType: [],
    resistanceType: [],
    absorbType: [],
    manaCost: 0,
    cooldown: 0,
    maxLevel: 5,
    price: 15,
    currency: Currency.LEVEL,
  },
  {
    title: "VEIN MINER",
    type: [EnchantType.PICKAXE],
    description: "Mine veins of ores",
    damageType: [],
    resistanceType: [],
    absorbType: [],
    manaCost: 0,
    cooldown: 0,
    maxLevel: 5,
    price: 15,
    currency: Currency.LEVEL,
  },
  {
    title: "DEFORESTATION",
    type: [EnchantType.AXE],
    description: "Cut the whole vertical tree trunk",
    damageType: [],
    resistanceType: [],
    absorbType: [],
    manaCost: 0,
    cooldown: 0,
    maxLevel: 5,
    price: 15,
    currency: Currency.LEVEL,
  },
  {
    title: "AUTO REPAIR",
    type: [EnchantType.GENERAL],
    description: "Slowly repair tool/weapon/armor over time",
    damageType: [],
    resistanceType: [],
    absorbType: [],
    manaCost: 0,
    cooldown: 0,
    maxLevel: 5,
    price: 30,
    currency: Currency.LEVEL,
  },
  {
    title: "SUPER NOVA",
    type: [EnchantType.MAGIC_WAND],
    description: "Deal huge magic damage on surrounding area",
    damageType: [DamageType.MAGICAL_DMG],
    resistanceType: [ResistanceType.MAGICAL_RESIST],
    absorbType: [],
    manaCost: 15,
    cooldown: 40,
    maxLevel: 5,
    price: 75,
    currency: Currency.LEVEL,
  },
  {
    title: "LIGHTNING",
    type: [EnchantType.MAGIC_WAND],
    description: "Strike lightning on surrounding area",
    damageType: [DamageType.MAGICAL_DMG],
    resistanceType: [ResistanceType.MAGICAL_RESIST],
    absorbType: [],
    manaCost: 12.5,
    cooldown: 25,
    maxLevel: 5,
    price: 55,
    currency: Currency.LEVEL,
  },
  {
    title: "HEALING",
    type: [EnchantType.MAGIC_WAND],
    description: "Heal yourself and your allies on surrounding area",
    damageType: [],
    resistanceType: [],
    absorbType: [],
    manaCost: 13.2,
    cooldown: 50,
    maxLevel: 3,
    price: 45,
    currency: Currency.LEVEL,
  },
  {
    title: "LEVITATE",
    type: [EnchantType.MAGIC_WAND],
    description: "Levitate Enemies and deal magic damage",
    damageType: [DamageType.MAGICAL_DMG, DamageType.PHYSICAL_DMG],
    resistanceType: [
      ResistanceType.MAGICAL_RESIST,
      ResistanceType.PHYSICAL_RESIST,
    ],
    absorbType: [],
    manaCost: 8.2,
    cooldown: 35,
    maxLevel: 3,
    price: 60,
    currency: Currency.LEVEL,
  },
  {
    title: "NEBULA",
    type: [EnchantType.MAGIC_WAND],
    description: "Nebula explosion!",
    damageType: [DamageType.MAGICAL_DMG],
    resistanceType: [ResistanceType.MAGICAL_RESIST],
    absorbType: [],
    manaCost: 17.3,
    cooldown: 45,
    maxLevel: 8,
    price: 150,
    currency: Currency.LEVEL,
  },
  {
    title: "SHARP ARROW",
    type: [EnchantType.BOW],
    description: "Deal more ranged damage",
    damageType: [DamageType.PHYSICAL_DMG],
    resistanceType: [ResistanceType.PHYSICAL_RESIST],
    absorbType: [],
    manaCost: 0,
    cooldown: 0,
    maxLevel: 10,
    price: 35,
    currency: Currency.LEVEL,
  },
  {
    title: "STUN",
    type: [EnchantType.BOW],
    description: "Get a chance to stun the enemy",
    damageType: [DamageType.PHYSICAL_DMG],
    resistanceType: [ResistanceType.PHYSICAL_RESIST],
    absorbType: [],
    manaCost: 0,
    cooldown: 0,
    maxLevel: 3,
    price: 53,
    currency: Currency.LEVEL,
  },
  {
    title: "FROST ARROW",
    type: [EnchantType.BOW],
    description: "Slow your enemy by chance",
    damageType: [DamageType.PHYSICAL_DMG],
    resistanceType: [ResistanceType.PHYSICAL_RESIST],
    absorbType: [],
    manaCost: 0,
    cooldown: 0,
    maxLevel: 5,
    price: 43,
    currency: Currency.LEVEL,
  },
  {
    title: "FOCUS FIRE",
    type: [EnchantType.BOW],
    description:
      "Gain Quick Movement Speed and Invisibility on every success hit",
    damageType: [DamageType.PHYSICAL_DMG],
    resistanceType: [ResistanceType.PHYSICAL_RESIST],
    absorbType: [],
    manaCost: 0,
    cooldown: 0,
    maxLevel: 3,
    price: 58,
    currency: Currency.LEVEL,
  },
  {
    title: "DEATH ANGEL",
    type: [EnchantType.BOW],
    description: "Fall a meteorite to where the arrow landed",
    damageType: [DamageType.PHYSICAL_DMG],
    resistanceType: [ResistanceType.PHYSICAL_RESIST],
    absorbType: [],
    manaCost: 8,
    cooldown: 30,
    maxLevel: 5,
    price: 75,
    currency: Currency.LEVEL,
  },
  {
    title: "IMPLANT",
    type: [EnchantType.BOW],
    description: "The dark matter will give a strength to your bow",
    damageType: [DamageType.PHYSICAL_DMG],
    resistanceType: [ResistanceType.PHYSICAL_RESIST],
    absorbType: [],
    manaCost: 8,
    cooldown: 30,
    maxLevel: 5,
    price: 93,
    currency: Currency.LEVEL,
  },
  {
    title: "STORM",
    type: [EnchantType.MAGIC_WAND],
    description: "The power of wind and storm will bind your wand",
    damageType: [DamageType.MAGICAL_DMG, DamageType.MAGICAL_PEN],
    resistanceType: [ResistanceType.MAGICAL_RESIST],
    absorbType: [],
    manaCost: 20,
    cooldown: 200,
    maxLevel: 15,
    price: 140,
    currency: Currency.LEVEL,
  },
  {
    title: "MANA SHIELD",
    type: [EnchantType.SHIELD],
    description: "Absorb full damage and consume it as mana",
    damageType: [],
    resistanceType: [
      ResistanceType.PHYSICAL_RESIST,
      ResistanceType.MAGICAL_RESIST,
    ],
    absorbType: [],
    manaCost: 0,
    cooldown: 0,
    maxLevel: 12,
    price: 48,
    currency: Currency.LEVEL,
  },
  {
    title: "MANA BURN",
    type: [EnchantType.MAGIC_WAND],
    description: "Burn players mana within the surrounding area",
    damageType: [],
    resistanceType: [],
    absorbType: [],
    manaCost: 0,
    cooldown: 0,
    maxLevel: 5,
    price: 48,
    currency: Currency.LEVEL,
  },
  {
    title: "STURDY",
    type: [EnchantType.SHIELD],
    description: "Obtain physical resistance when equipped offhand",
    damageType: [],
    resistanceType: [ResistanceType.PHYSICAL_RESIST],
    absorbType: [],
    manaCost: 0,
    cooldown: 0,
    maxLevel: 5,
    price: 50,
    currency: Currency.LEVEL,
  },
  {
    title: "DEATH RAY",
    type: [EnchantType.BOW],
    description: "Shoot laser on target",
    damageType: [DamageType.PHYSICAL_DMG],
    resistanceType: [ResistanceType.PHYSICAL_RESIST],
    absorbType: [],
    manaCost: 0,
    cooldown: 0,
    maxLevel: 3,
    price: 85,
    currency: Currency.LEVEL,
  },
  {
    title: "BLINK",
    type: [EnchantType.BOOTS],
    description: "Shift + Right click on a target to blink on a short distance",
    damageType: [],
    resistanceType: [],
    absorbType: [],
    manaCost: 0,
    cooldown: 0,
    maxLevel: 3,
    price: 35,
    currency: Currency.LEVEL,
  },
  {
    title: "JUGGERNAUT",
    type: [EnchantType.SWORD],
    description: "Deal armor penetration",
    damageType: [DamageType.PHYSICAL_DMG, DamageType.PHYSICAL_DMG_CRIT],
    resistanceType: [ResistanceType.PHYSICAL_RESIST],
    absorbType: [],
    manaCost: 0,
    cooldown: 0,
    maxLevel: 8,
    price: 70,
    currency: Currency.LEVEL,
  },
  {
    title: "WIND SLASHER",
    type: [EnchantType.SWORD],
    description: "Summon tornado by chance at AGILITY 40+",
    damageType: [DamageType.PHYSICAL_DMG],
    resistanceType: [ResistanceType.PHYSICAL_RESIST],
    absorbType: [],
    manaCost: 0,
    cooldown: 0,
    maxLevel: 3,
    price: 55,
    currency: Currency.LEVEL,
  },
  {
    title: "FIREBALL",
    type: [EnchantType.MAGIC_WAND],
    description: "Shoot fireball on a target",
    damageType: [DamageType.MAGICAL_DMG],
    resistanceType: [ResistanceType.MAGICAL_RESIST],
    absorbType: [],
    manaCost: 5,
    cooldown: 0,
    maxLevel: 10,
    price: 20,
    currency: Currency.LEVEL,
  },
  {
    title: "STELLA",
    type: [EnchantType.BOW],
    description: "Ultimate bow enchantment",
    damageType: [DamageType.MAGICAL_DMG, DamageType.PHYSICAL_DMG],
    resistanceType: [ResistanceType.MAGICAL_RESIST, DamageType.PHYSICAL_DMG],
    absorbType: [],
    manaCost: 0,
    cooldown: 300,
    maxLevel: 1,
    price: 125,
    currency: Currency.LEVEL,
  },
  {
    title: "FARMLAND",
    type: [EnchantType.HOE],
    description: "Create a small chunk of farmland",
    damageType: [],
    resistanceType: [],
    absorbType: [],
    manaCost: 0,
    cooldown: 0,
    maxLevel: 2,
    price: 25,
    currency: Currency.LEVEL,
  },
  {
    title: "BLACK HOLE",
    type: [EnchantType.MAGIC_WAND],
    description: "Cast a black hole on your area, trapping players",
    damageType: [DamageType.MAGICAL_DMG],
    resistanceType: [ResistanceType.MAGICAL_RESIST],
    absorbType: [],
    manaCost: 25.2,
    cooldown: 450,
    maxLevel: 5,
    price: 750,
    currency: Currency.RACO,
  },
  {
    title: "TELEPATHY",
    type: [EnchantType.TOOLS],
    description:
      "Collect dropped item instantly from being mined (Incompatible with fortune enchantment)",
    damageType: [],
    resistanceType: [],
    absorbType: [],
    manaCost: 0,
    cooldown: 0,
    maxLevel: 1,
    price: 30,
    currency: Currency.LEVEL,
  },
  {
    title: "CONFUSION",
    type: [EnchantType.SWORD],
    description: "Confuse the enemy by chance",
    damageType: [DamageType.PHYSICAL_DMG],
    resistanceType: [ResistanceType.PHYSICAL_RESIST],
    absorbType: [],
    manaCost: 0,
    cooldown: 0,
    maxLevel: 3,
    price: 27,
    currency: Currency.LEVEL,
  },
  {
    title: "DRAGON BREATH",
    type: [EnchantType.SWORD, EnchantType.SPEAR],
    description: "Inflict your enemies on fire in a radius",
    damageType: [DamageType.PHYSICAL_DMG, DamageType.MAGICAL_DMG],
    resistanceType: [
      ResistanceType.PHYSICAL_RESIST,
      ResistanceType.PHYSICAL_RESIST,
    ],
    absorbType: [],
    manaCost: 0,
    cooldown: 0,
    maxLevel: 5,
    price: 32,
    currency: Currency.LEVEL,
  },
  {
    title: "HEIST",
    type: [EnchantType.SWORD],
    description: "Get a chance to steal money from your enemy",
    damageType: [DamageType.PHYSICAL_DMG],
    resistanceType: [ResistanceType.PHYSICAL_RESIST],
    absorbType: [],
    manaCost: 0,
    cooldown: 0,
    maxLevel: 5,
    price: 300,
    currency: Currency.RACO,
  },
  {
    title: "ANTI HEIST",
    type: [EnchantType.CHESTPLATE],
    description: "Get a chance to block heist enchantment from attacker",
    damageType: [],
    resistanceType: [],
    absorbType: [],
    manaCost: 0,
    cooldown: 0,
    maxLevel: 3,
    price: 450,
    currency: Currency.RACO,
  },
  {
    title: "MAGNETIC",
    type: [EnchantType.GENERAL],
    description: "Attracts ground items nearby to pickup",
    damageType: [],
    resistanceType: [],
    absorbType: [],
    manaCost: 0,
    cooldown: 0,
    maxLevel: 2,
    price: 20,
    currency: Currency.RACO,
  },
  {
    title: "BRILLIANCE",
    type: [EnchantType.HELMET],
    description: "Grant mana regeneration",
    damageType: [],
    resistanceType: [],
    absorbType: [],
    manaCost: 0,
    cooldown: 0,
    maxLevel: 8,
    price: 125,
    currency: Currency.RACO,
  },
  {
    title: "GOOEY",
    type: [EnchantType.SWORD, EnchantType.SPEAR],
    description: "Get a chance to launch your enemy 8 blocks above",
    damageType: [DamageType.PHYSICAL_DMG],
    resistanceType: [ResistanceType.PHYSICAL_RESIST],
    absorbType: [],
    manaCost: 0,
    cooldown: 0,
    maxLevel: 8,
    price: 30,
    currency: Currency.LEVEL,
  },
  {
    title: "COMPANION HEALING",
    type: [EnchantType.ANIMAL_ARMOR],
    description:
      "Slowly heals your companion [Applies to horse and wolf armor]",
    damageType: [],
    resistanceType: [],
    absorbType: [],
    manaCost: 0,
    cooldown: 0,
    maxLevel: 5,
    price: 5,
    currency: Currency.LEVEL,
  },
  {
    title: "COMPANION THORNS",
    type: [EnchantType.ANIMAL_ARMOR],
    description:
      "Applies thorns and slowness effect to the attacker [Applies to horse and wolf armor]",
    damageType: [],
    resistanceType: [],
    absorbType: [],
    manaCost: 0,
    cooldown: 0,
    maxLevel: 5,
    price: 10,
    currency: Currency.LEVEL,
  },
  {
    title: "STEALTH",
    type: [EnchantType.SWORD, EnchantType.SPEAR],
    description: "Deals additional 10% damager per level while on sneak",
    damageType: [DamageType.PHYSICAL_DMG],
    resistanceType: [ResistanceType.PHYSICAL_RESIST],
    absorbType: [],
    manaCost: 0,
    cooldown: 0,
    maxLevel: 5,
    price: 15,
    currency: Currency.LEVEL,
  },

  // --------------------------------------------------------------- 1.5.0
  // 76 new enchantments: 23 tools, 30 weapons, 23 armor.

  // Tools
  {
    title: "Lodefinder",
    type: [EnchantType.PICKAXE],
    description:
      "Breaking stone has a chance to outline every ore block nearby in glowing particles for 4 seconds",
    damageType: [],
    resistanceType: [],
    absorbType: [],
    manaCost: 0,
    cooldown: 6,
    maxLevel: 5,
    price: 40,
    currency: Currency.LEVEL,
  },
  {
    title: "Kilnfire",
    type: [EnchantType.PICKAXE, EnchantType.AXE],
    description:
      "Ore and sand blocks drop their smelted result instead of the raw drop",
    damageType: [],
    resistanceType: [],
    absorbType: [],
    manaCost: 0,
    cooldown: 0,
    maxLevel: 4,
    price: 35,
    currency: Currency.LEVEL,
  },
  {
    title: "Loam Sense",
    type: [EnchantType.HOE],
    description:
      "Right click farmland to soak the whole area to full moisture and bone meal a few crops",
    damageType: [],
    resistanceType: [],
    absorbType: [],
    manaCost: 0,
    cooldown: 15,
    maxLevel: 3,
    price: 22,
    currency: Currency.LEVEL,
  },
  {
    title: "Root Rot",
    type: [EnchantType.AXE],
    description:
      "Leaves around a broken log decay at once, with better sapling and apple drops",
    damageType: [],
    resistanceType: [],
    absorbType: [],
    manaCost: 0,
    cooldown: 0,
    maxLevel: 5,
    price: 28,
    currency: Currency.LEVEL,
  },
  {
    title: "Deep Tally",
    type: [EnchantType.PICKAXE, EnchantType.SHOVEL],
    description:
      "Blocks broken below y=48 grant bonus CE experience, more the deeper you go",
    damageType: [],
    resistanceType: [],
    absorbType: [],
    manaCost: 0,
    cooldown: 0,
    maxLevel: 10,
    price: 30,
    currency: Currency.LEVEL,
  },
  {
    title: "Sifting Hands",
    type: [EnchantType.SHOVEL],
    description:
      "Gravel, sand and dirt have a chance to yield a bonus drop, very occasionally a treasure item",
    damageType: [],
    resistanceType: [],
    absorbType: [],
    manaCost: 0,
    cooldown: 0,
    maxLevel: 7,
    price: 26,
    currency: Currency.LEVEL,
  },
  {
    title: "Toolmarrow",
    type: [EnchantType.GENERAL],
    description:
      "Chance to skip durability loss entirely, up to 40% at max level",
    damageType: [],
    resistanceType: [],
    absorbType: [],
    manaCost: 0,
    cooldown: 0,
    maxLevel: 5,
    price: 45,
    currency: Currency.LEVEL,
  },
  {
    title: "Brinepull",
    type: [EnchantType.FISHING_ROD],
    description:
      "Shortens the fishing bite wait and gives a chance at a second catch",
    damageType: [],
    resistanceType: [],
    absorbType: [],
    manaCost: 0,
    cooldown: 0,
    maxLevel: 4,
    price: 18,
    currency: Currency.LEVEL,
  },
  {
    title: "Slagheap",
    type: [EnchantType.PICKAXE],
    description:
      "Junk blocks are discarded for CE experience instead of filling your bag. Sneak to keep them",
    damageType: [],
    resistanceType: [],
    absorbType: [],
    manaCost: 0,
    cooldown: 0,
    maxLevel: 3,
    price: 24,
    currency: Currency.LEVEL,
  },
  {
    title: "Widebore",
    type: [EnchantType.PICKAXE],
    description: "Mines a 3x3 at level 2 and a 3x3 two blocks deep at level 3",
    damageType: [],
    resistanceType: [],
    absorbType: [],
    manaCost: 0,
    cooldown: 0,
    maxLevel: 3,
    price: 50,
    currency: Currency.LEVEL,
  },
  {
    title: "Quarryjack",
    type: [EnchantType.PICKAXE],
    description: "Builds up Haste the longer you keep digging without stopping",
    damageType: [],
    resistanceType: [],
    absorbType: [],
    manaCost: 0,
    cooldown: 0,
    maxLevel: 6,
    price: 38,
    currency: Currency.LEVEL,
  },
  {
    title: "Stonemason",
    type: [EnchantType.PICKAXE],
    description:
      "Stone type blocks drop their worked variant instead of the raw one",
    damageType: [],
    resistanceType: [],
    absorbType: [],
    manaCost: 0,
    cooldown: 0,
    maxLevel: 4,
    price: 20,
    currency: Currency.LEVEL,
  },
  {
    title: "Seedwake",
    type: [EnchantType.AXE],
    description:
      "Breaking a log replants a matching sapling from your inventory below it",
    damageType: [],
    resistanceType: [],
    absorbType: [],
    manaCost: 0,
    cooldown: 0,
    maxLevel: 3,
    price: 20,
    currency: Currency.LEVEL,
  },
  {
    title: "Splitgrain",
    type: [EnchantType.AXE],
    description:
      "Logs drop planks directly, more of them than crafting would give you",
    damageType: [],
    resistanceType: [],
    absorbType: [],
    manaCost: 0,
    cooldown: 0,
    maxLevel: 4,
    price: 24,
    currency: Currency.LEVEL,
  },
  {
    title: "Deadfall",
    type: [EnchantType.AXE],
    description:
      "Fell a tree holding a beehive without upsetting the bees, hive and honey intact",
    damageType: [],
    resistanceType: [],
    absorbType: [],
    manaCost: 0,
    cooldown: 0,
    maxLevel: 3,
    price: 16,
    currency: Currency.LEVEL,
  },
  {
    title: "Scytheswing",
    type: [EnchantType.HOE],
    description:
      "Harvests every fully grown crop in the row at once and leaves the young ones alone",
    damageType: [],
    resistanceType: [],
    absorbType: [],
    manaCost: 0,
    cooldown: 0,
    maxLevel: 5,
    price: 42,
    currency: Currency.LEVEL,
  },
  {
    title: "Drillseed",
    type: [EnchantType.HOE],
    description:
      "Right click farmland to plant seeds into every empty block around you",
    damageType: [],
    resistanceType: [],
    absorbType: [],
    manaCost: 0,
    cooldown: 0,
    maxLevel: 4,
    price: 30,
    currency: Currency.LEVEL,
  },
  {
    title: "Trenchline",
    type: [EnchantType.SHOVEL],
    description:
      "Digs a straight line of blocks in the direction you are facing",
    damageType: [],
    resistanceType: [],
    absorbType: [],
    manaCost: 0,
    cooldown: 0,
    maxLevel: 3,
    price: 28,
    currency: Currency.LEVEL,
  },
  {
    title: "Backfill",
    type: [EnchantType.SHOVEL],
    description:
      "Sneak right click to place blocks you are carrying into the gap you are looking at",
    damageType: [],
    resistanceType: [],
    absorbType: [],
    manaCost: 0,
    cooldown: 0,
    maxLevel: 4,
    price: 22,
    currency: Currency.LEVEL,
  },
  {
    title: "Rodwhip",
    type: [EnchantType.FISHING_ROD],
    description:
      "Hooking a living entity yanks it toward you and deals damage on the pull",
    damageType: [DamageType.PHYSICAL_DMG],
    resistanceType: [ResistanceType.PHYSICAL_RESIST],
    absorbType: [],
    manaCost: 0,
    cooldown: 0,
    maxLevel: 5,
    price: 34,
    currency: Currency.LEVEL,
  },
  {
    title: "Slackjaw",
    type: [EnchantType.FISHING_ROD],
    description:
      "A hooked entity gets Weakness II and cannot sprint while the hook holds",
    damageType: [],
    resistanceType: [],
    absorbType: [],
    manaCost: 0,
    cooldown: 0,
    maxLevel: 4,
    price: 26,
    currency: Currency.LEVEL,
  },
  {
    title: "Ironmonger",
    type: [EnchantType.TOOLS],
    description:
      "Cheaper anvil repairs, and more anvil work before the item hits Too Expensive",
    damageType: [],
    resistanceType: [],
    absorbType: [],
    manaCost: 0,
    cooldown: 0,
    maxLevel: 5,
    price: 40,
    currency: Currency.LEVEL,
  },
  {
    title: "Hairsbreadth",
    type: [EnchantType.GENERAL],
    description:
      "The item stops at 1 durability instead of breaking, and limps back a little at higher levels",
    damageType: [],
    resistanceType: [],
    absorbType: [],
    manaCost: 0,
    cooldown: 0,
    maxLevel: 3,
    price: 55,
    currency: Currency.LEVEL,
  },

  // Weapons
  {
    title: "Ashen Grip",
    type: [EnchantType.SWORD, EnchantType.SPEAR],
    description:
      "Chance to set the target alight, and the fire jumps to one other hostile nearby",
    damageType: [],
    resistanceType: [],
    absorbType: [],
    manaCost: 0,
    cooldown: 0,
    maxLevel: 5,
    price: 62,
    currency: Currency.LEVEL,
  },
  {
    title: "Grudgework",
    type: [EnchantType.SWORD, EnchantType.MACE],
    description:
      "Consecutive hits on the same target stack bonus damage, up to 5 stacks",
    damageType: [DamageType.PHYSICAL_DMG],
    resistanceType: [ResistanceType.PHYSICAL_RESIST],
    absorbType: [],
    manaCost: 0,
    cooldown: 0,
    maxLevel: 7,
    price: 68,
    currency: Currency.LEVEL,
  },
  {
    title: "Tendonsnap",
    type: [EnchantType.SPEAR, EnchantType.MACE],
    description: "Chance to cancel the target's sprint and apply Slowness III",
    damageType: [],
    resistanceType: [],
    absorbType: [],
    manaCost: 0,
    cooldown: 0,
    maxLevel: 3,
    price: 44,
    currency: Currency.LEVEL,
  },
  {
    title: "Ribcracker",
    type: [EnchantType.MACE],
    description:
      "Turns your fall distance into bonus mace damage and slows whatever you land on",
    damageType: [DamageType.PHYSICAL_DMG],
    resistanceType: [ResistanceType.PHYSICAL_RESIST],
    absorbType: [],
    manaCost: 0,
    cooldown: 0,
    maxLevel: 4,
    price: 58,
    currency: Currency.LEVEL,
  },
  {
    title: "Hollow Toll",
    type: [EnchantType.SWORD],
    description:
      "Killing a mob applies Weakness I to every mob of the same type nearby",
    damageType: [],
    resistanceType: [],
    absorbType: [],
    manaCost: 0,
    cooldown: 0,
    maxLevel: 4,
    price: 54,
    currency: Currency.LEVEL,
  },
  {
    title: "Sawtooth",
    type: [EnchantType.SWORD, EnchantType.SPEAR],
    description:
      "Each hit shreds the target's armor effectiveness for 5 seconds, up to 3 stacks",
    damageType: [DamageType.PHYSICAL_DMG],
    resistanceType: [ResistanceType.PHYSICAL_RESIST],
    absorbType: [],
    manaCost: 0,
    cooldown: 0,
    maxLevel: 5,
    price: 60,
    currency: Currency.LEVEL,
  },
  {
    title: "Widowcut",
    type: [EnchantType.SWORD],
    description:
      "Bonus damage that scales with how empty your mana bar is, best on a warrior who never spends it",
    damageType: [DamageType.PHYSICAL_DMG],
    resistanceType: [ResistanceType.PHYSICAL_RESIST],
    absorbType: [],
    manaCost: 0,
    cooldown: 0,
    maxLevel: 5,
    price: 58,
    currency: Currency.LEVEL,
  },
  {
    title: "Bloodtithe",
    type: [EnchantType.SWORD, EnchantType.SPEAR],
    description:
      "Every swing costs you a heart and pays back far more damage. Will not drop you below 2 hearts",
    damageType: [DamageType.PHYSICAL_DMG],
    resistanceType: [ResistanceType.PHYSICAL_RESIST],
    absorbType: [],
    manaCost: 0,
    cooldown: 0,
    maxLevel: 5,
    price: 64,
    currency: Currency.LEVEL,
  },
  {
    title: "Ironjaw",
    type: [EnchantType.SWORD, EnchantType.MACE],
    description:
      "Guarantees a floor of damage that no amount of defence can reduce away",
    damageType: [DamageType.PHYSICAL_DMG],
    resistanceType: [],
    absorbType: [],
    manaCost: 0,
    cooldown: 0,
    maxLevel: 5,
    price: 70,
    currency: Currency.LEVEL,
  },
  {
    title: "Lancework",
    type: [EnchantType.SPEAR],
    description:
      "The hit also strikes whoever is standing directly behind the target, for half damage",
    damageType: [DamageType.PHYSICAL_DMG],
    resistanceType: [ResistanceType.PHYSICAL_RESIST],
    absorbType: [],
    manaCost: 0,
    cooldown: 0,
    maxLevel: 5,
    price: 56,
    currency: Currency.LEVEL,
  },
  {
    title: "Cleaverhand",
    type: [EnchantType.MACE],
    description:
      "Chance to apply Mining Fatigue III and interrupt whatever the target was doing",
    damageType: [],
    resistanceType: [],
    absorbType: [],
    manaCost: 0,
    cooldown: 0,
    maxLevel: 4,
    price: 52,
    currency: Currency.LEVEL,
  },
  {
    title: "Skullsplit",
    type: [EnchantType.MACE],
    description: "A killing blow has a chance to leave the victim's head",
    damageType: [],
    resistanceType: [],
    absorbType: [],
    manaCost: 0,
    cooldown: 0,
    maxLevel: 3,
    price: 45,
    currency: Currency.LEVEL,
  },
  {
    title: "Tidewrack",
    type: [EnchantType.TRIDENT],
    description:
      "A thrown trident leaves a whirlpool that pulls everything nearby toward its centre",
    damageType: [],
    resistanceType: [],
    absorbType: [],
    manaCost: 0,
    cooldown: 0,
    maxLevel: 3,
    price: 72,
    currency: Currency.LEVEL,
  },
  {
    title: "Stormhook",
    type: [EnchantType.TRIDENT],
    description:
      "A thrown trident that hits a living entity drags it back toward you",
    damageType: [],
    resistanceType: [],
    absorbType: [],
    manaCost: 0,
    cooldown: 0,
    maxLevel: 4,
    price: 65,
    currency: Currency.LEVEL,
  },
  {
    title: "Bargewake",
    type: [EnchantType.TRIDENT],
    description:
      "Trident damage goes up while you are in water, in rain or in a thunderstorm",
    damageType: [DamageType.PHYSICAL_DMG],
    resistanceType: [ResistanceType.PHYSICAL_RESIST],
    absorbType: [],
    manaCost: 0,
    cooldown: 0,
    maxLevel: 5,
    price: 48,
    currency: Currency.LEVEL,
  },
  {
    title: "Skipstone",
    type: [EnchantType.TRIDENT],
    description:
      "A thrown trident ricochets off a block into the nearest enemy, at 70% damage",
    damageType: [DamageType.PHYSICAL_DMG],
    resistanceType: [ResistanceType.PHYSICAL_RESIST],
    absorbType: [],
    manaCost: 0,
    cooldown: 0,
    maxLevel: 3,
    price: 55,
    currency: Currency.LEVEL,
  },
  {
    title: "Quiverburst",
    type: [EnchantType.BOW],
    description:
      "Every few shots the bow releases two extra arrows, free from your inventory",
    damageType: [DamageType.PHYSICAL_DMG],
    resistanceType: [ResistanceType.PHYSICAL_RESIST],
    absorbType: [],
    manaCost: 0,
    cooldown: 0,
    maxLevel: 5,
    price: 66,
    currency: Currency.LEVEL,
  },
  {
    title: "Marrowshot",
    type: [EnchantType.BOW],
    description:
      "Arrow hits ignore part of the target's magic defence, up to 24%",
    damageType: [DamageType.MAGICAL_PEN],
    resistanceType: [ResistanceType.MAGICAL_RESIST],
    absorbType: [],
    manaCost: 0,
    cooldown: 0,
    maxLevel: 6,
    price: 400,
    currency: Currency.RACO,
  },
  {
    title: "Longdraw",
    type: [EnchantType.BOW],
    description:
      "Holding a fully drawn bow a beat longer adds damage on release",
    damageType: [DamageType.PHYSICAL_DMG],
    resistanceType: [ResistanceType.PHYSICAL_RESIST],
    absorbType: [],
    manaCost: 0,
    cooldown: 0,
    maxLevel: 6,
    price: 62,
    currency: Currency.LEVEL,
  },
  {
    title: "Skimshot",
    type: [EnchantType.BOW],
    description:
      "An arrow that hits a block bounces once toward the nearest hostile",
    damageType: [DamageType.PHYSICAL_DMG],
    resistanceType: [ResistanceType.PHYSICAL_RESIST],
    absorbType: [],
    manaCost: 0,
    cooldown: 0,
    maxLevel: 4,
    price: 50,
    currency: Currency.LEVEL,
  },
  {
    title: "Tetherline",
    type: [EnchantType.BOW],
    description:
      "Ties the target to the spot it was hit, it cannot move more than 4 blocks away",
    damageType: [],
    resistanceType: [],
    absorbType: [],
    manaCost: 0,
    cooldown: 0,
    maxLevel: 4,
    price: 70,
    currency: Currency.LEVEL,
  },
  {
    title: "Ashfletch",
    type: [EnchantType.BOW],
    description:
      "The arrow leaves a cloud of ash that blinds and slows everything inside it",
    damageType: [],
    resistanceType: [],
    absorbType: [],
    manaCost: 0,
    cooldown: 0,
    maxLevel: 5,
    price: 58,
    currency: Currency.LEVEL,
  },
  {
    title: "Emberwake",
    type: [EnchantType.MAGIC_WAND],
    description:
      "Lays a line of fire runes that burn any living entity walking into them",
    damageType: [DamageType.MAGICAL_DMG],
    resistanceType: [ResistanceType.MAGICAL_RESIST],
    absorbType: [],
    manaCost: 11,
    cooldown: 30,
    maxLevel: 8,
    price: 95,
    currency: Currency.LEVEL,
  },
  {
    title: "Glasswind",
    type: [EnchantType.MAGIC_WAND],
    description:
      "A short cold cone that deals magic damage and knocks everything in it back",
    damageType: [DamageType.MAGICAL_DMG],
    resistanceType: [ResistanceType.MAGICAL_RESIST],
    absorbType: [],
    manaCost: 4,
    cooldown: 8,
    maxLevel: 6,
    price: 50,
    currency: Currency.LEVEL,
  },
  {
    title: "Sundial",
    type: [EnchantType.MAGIC_WAND],
    description:
      "Slows every hostile around you and gives you and your allies Speed. No damage",
    damageType: [],
    resistanceType: [],
    absorbType: [],
    manaCost: 16,
    cooldown: 60,
    maxLevel: 4,
    price: 550,
    currency: Currency.RACO,
  },
  {
    title: "Gravewell",
    type: [EnchantType.MAGIC_WAND],
    description:
      "Opens a patch of ground that drains hostiles and heals you, capped so it cannot be farmed",
    damageType: [DamageType.MAGICAL_DMG],
    resistanceType: [ResistanceType.MAGICAL_RESIST],
    absorbType: [],
    manaCost: 18,
    cooldown: 70,
    maxLevel: 7,
    price: 300,
    currency: Currency.RACO,
  },
  {
    title: "Mirrorstep",
    type: [EnchantType.MAGIC_WAND],
    description:
      "Swaps places with the living entity you are looking at, and refunds the mana if it would suffocate you",
    damageType: [],
    resistanceType: [],
    absorbType: [],
    manaCost: 12,
    cooldown: 45,
    maxLevel: 5,
    price: 88,
    currency: Currency.LEVEL,
  },
  {
    title: "Cindershroud",
    type: [EnchantType.MAGIC_WAND],
    description:
      "Reduces the damage you take for a few seconds and sets melee attackers alight",
    damageType: [],
    resistanceType: [],
    absorbType: [DamageType.PHYSICAL_DMG, DamageType.MAGICAL_DMG],
    manaCost: 14,
    cooldown: 55,
    maxLevel: 6,
    price: 76,
    currency: Currency.LEVEL,
  },
  {
    title: "Chainarc",
    type: [EnchantType.MAGIC_WAND],
    description:
      "A bolt that jumps between targets, losing strength on every jump",
    damageType: [DamageType.MAGICAL_DMG],
    resistanceType: [ResistanceType.MAGICAL_RESIST],
    absorbType: [],
    manaCost: 15.5,
    cooldown: 40,
    maxLevel: 9,
    price: 110,
    currency: Currency.LEVEL,
  },
  {
    title: "Hushfall",
    type: [EnchantType.MAGIC_WAND],
    description:
      "The target cannot shoot, teleport or cast for a few seconds. Takes the trick away, not the health",
    damageType: [],
    resistanceType: [],
    absorbType: [],
    manaCost: 13,
    cooldown: 65,
    maxLevel: 4,
    price: 92,
    currency: Currency.LEVEL,
  },

  // Armor
  {
    title: "Rekindle",
    type: [EnchantType.CHESTPLATE],
    description:
      "Below 25% health you get Regeneration II and Speed I, once every few minutes",
    damageType: [],
    resistanceType: [],
    absorbType: [],
    manaCost: 0,
    cooldown: 165,
    maxLevel: 4,
    price: 74,
    currency: Currency.LEVEL,
  },
  {
    title: "Ballast",
    type: [EnchantType.BOOTS],
    description:
      "Reduces knockback taken and cancels fall damage entirely on short falls",
    damageType: [],
    resistanceType: [],
    absorbType: [],
    manaCost: 0,
    cooldown: 0,
    maxLevel: 5,
    price: 40,
    currency: Currency.LEVEL,
  },
  {
    title: "Cinderstep",
    type: [EnchantType.BOOTS],
    description:
      "After a fire or lava hit, further burn damage is reduced for 3 seconds",
    damageType: [],
    resistanceType: [],
    absorbType: [],
    manaCost: 0,
    cooldown: 0,
    maxLevel: 4,
    price: 46,
    currency: Currency.LEVEL,
  },
  {
    title: "Nightglass",
    type: [EnchantType.HELMET],
    description:
      "Night Vision in the dark, and Blindness and Darkness wear off faster",
    damageType: [],
    resistanceType: [],
    absorbType: [],
    manaCost: 0,
    cooldown: 0,
    maxLevel: 3,
    price: 30,
    currency: Currency.LEVEL,
  },
  {
    title: "Quillmail",
    type: [EnchantType.LEGGINGS],
    description:
      "Melee attackers take magic damage back, so their armor does not help them",
    damageType: [DamageType.MAGICAL_DMG],
    resistanceType: [ResistanceType.MAGICAL_RESIST],
    absorbType: [],
    manaCost: 0,
    cooldown: 0,
    maxLevel: 6,
    price: 55,
    currency: Currency.LEVEL,
  },
  {
    title: "Bulwark Oath",
    type: [EnchantType.SHIELD],
    description:
      "While you are blocking, allies within 5 blocks take less damage from everything",
    damageType: [],
    resistanceType: [],
    absorbType: [],
    manaCost: 0,
    cooldown: 0,
    maxLevel: 5,
    price: 60,
    currency: Currency.LEVEL,
  },
  {
    title: "Saltcoat",
    type: [EnchantType.ARMORS],
    description:
      "Shortens every negative potion effect applied to you, up to 72%",
    damageType: [],
    resistanceType: [],
    absorbType: [],
    manaCost: 0,
    cooldown: 0,
    maxLevel: 8,
    price: 52,
    currency: Currency.LEVEL,
  },
  {
    title: "Barding Spirit",
    type: [EnchantType.ANIMAL_ARMOR],
    description:
      "Your wolf or horse gains max health and speed, and keeps up when it falls behind",
    damageType: [],
    resistanceType: [],
    absorbType: [],
    manaCost: 0,
    cooldown: 0,
    maxLevel: 6,
    price: 15,
    currency: Currency.LEVEL,
  },
  {
    title: "Waterlung",
    type: [EnchantType.HELMET],
    description:
      "More breath underwater, and no underwater mining penalty from level 3",
    damageType: [],
    resistanceType: [],
    absorbType: [],
    manaCost: 0,
    cooldown: 0,
    maxLevel: 4,
    price: 34,
    currency: Currency.LEVEL,
  },
  {
    title: "Crownward",
    type: [EnchantType.HELMET],
    description:
      "Reduces damage from arrows, tridents, fireballs and snowballs, up to 25%",
    damageType: [],
    resistanceType: [],
    absorbType: [DamageType.PHYSICAL_DMG],
    manaCost: 0,
    cooldown: 0,
    maxLevel: 5,
    price: 50,
    currency: Currency.LEVEL,
  },
  {
    title: "Hearsay",
    type: [EnchantType.HELMET],
    description:
      "Outlines the hostile mobs that have actually decided to come for you",
    damageType: [],
    resistanceType: [],
    absorbType: [],
    manaCost: 0,
    cooldown: 0,
    maxLevel: 4,
    price: 44,
    currency: Currency.LEVEL,
  },
  {
    title: "Slagplate",
    type: [EnchantType.CHESTPLATE],
    description:
      "Converts part of the physical damage you take into magic damage, for your wards to soak",
    damageType: [],
    resistanceType: [],
    absorbType: [DamageType.PHYSICAL_DMG],
    manaCost: 0,
    cooldown: 0,
    maxLevel: 5,
    price: 66,
    currency: Currency.LEVEL,
  },
  {
    title: "Backdraft",
    type: [EnchantType.CHESTPLATE],
    description:
      "A big hit throws every hostile off you and buys you a second of immunity",
    damageType: [],
    resistanceType: [],
    absorbType: [],
    manaCost: 0,
    cooldown: 20,
    maxLevel: 5,
    price: 58,
    currency: Currency.LEVEL,
  },
  {
    title: "Longcoat",
    type: [EnchantType.CHESTPLATE],
    description:
      "Reduces fall, fire, lava, drowning, suffocation, cactus, freezing and starvation damage",
    damageType: [],
    resistanceType: [],
    absorbType: [],
    manaCost: 0,
    cooldown: 0,
    maxLevel: 6,
    price: 54,
    currency: Currency.LEVEL,
  },
  {
    title: "Stridecut",
    type: [EnchantType.LEGGINGS],
    description:
      "Movement speed while you are at full health, fading away as you get hurt",
    damageType: [],
    resistanceType: [],
    absorbType: [],
    manaCost: 0,
    cooldown: 0,
    maxLevel: 5,
    price: 46,
    currency: Currency.LEVEL,
  },
  {
    title: "Sprintwell",
    type: [EnchantType.LEGGINGS],
    description:
      "Refills mana while you run, on top of your normal regeneration",
    damageType: [],
    resistanceType: [],
    absorbType: [],
    manaCost: 0,
    cooldown: 0,
    maxLevel: 8,
    price: 62,
    currency: Currency.LEVEL,
  },
  {
    title: "Deadweight",
    type: [EnchantType.LEGGINGS],
    description:
      "Refuses knockback, levitation and pulls, including the ones other CE enchantments cause at level 3",
    damageType: [],
    resistanceType: [],
    absorbType: [],
    manaCost: 0,
    cooldown: 0,
    maxLevel: 3,
    price: 68,
    currency: Currency.LEVEL,
  },
  {
    title: "Softfoot",
    type: [EnchantType.BOOTS],
    description:
      "Hostile mobs notice you from less distance, and your footsteps go quiet",
    damageType: [],
    resistanceType: [],
    absorbType: [],
    manaCost: 0,
    cooldown: 0,
    maxLevel: 5,
    price: 40,
    currency: Currency.LEVEL,
  },
  {
    title: "Downdraft",
    type: [EnchantType.BOOTS],
    description:
      "Sneak while falling to glide and steer, for a small mana drain per second",
    damageType: [],
    resistanceType: [],
    absorbType: [],
    manaCost: 0.4,
    cooldown: 0,
    maxLevel: 4,
    price: 52,
    currency: Currency.LEVEL,
  },
  {
    title: "Ripostewall",
    type: [EnchantType.SHIELD],
    description:
      "Sends part of the damage you blocked back through the shield, up to 75%",
    damageType: [DamageType.PHYSICAL_DMG],
    resistanceType: [ResistanceType.PHYSICAL_RESIST],
    absorbType: [],
    manaCost: 0,
    cooldown: 0,
    maxLevel: 5,
    price: 58,
    currency: Currency.LEVEL,
  },
  {
    title: "Anchorhold",
    type: [EnchantType.SHIELD],
    description:
      "No movement slowdown while blocking, and less knockback taken while you hold it up",
    damageType: [],
    resistanceType: [],
    absorbType: [],
    manaCost: 0,
    cooldown: 0,
    maxLevel: 4,
    price: 44,
    currency: Currency.LEVEL,
  },
  {
    title: "Wardweave",
    type: [EnchantType.ARMORS],
    description:
      "Each armor piece carrying this adds maximum mana, capped at +100 across the set",
    damageType: [],
    resistanceType: [],
    absorbType: [],
    manaCost: 0,
    cooldown: 0,
    maxLevel: 10,
    price: 200,
    currency: Currency.RACO,
  },
  {
    title: "Houndsense",
    type: [EnchantType.ANIMAL_ARMOR],
    description:
      "Your wolf or horse targets whatever last hurt you and hits it harder for 8 seconds",
    damageType: [],
    resistanceType: [],
    absorbType: [],
    manaCost: 0,
    cooldown: 0,
    maxLevel: 5,
    price: 18,
    currency: Currency.LEVEL,
  },

  // ------------------------------------------------------- added in 1.6.0
  {
    title: "Tallyscar",
    type: [EnchantType.SWORD, EnchantType.SPEAR],
    description:
      "Every hit leaves a mark on the victim, and the fifth mark bursts the whole tally at once",
    damageType: [DamageType.PHYSICAL_DMG],
    resistanceType: [ResistanceType.PHYSICAL_RESIST],
    absorbType: [],
    manaCost: 0,
    cooldown: 0,
    maxLevel: 5,
    price: 58,
    currency: Currency.LEVEL,
  },
  {
    title: "Coinbite",
    type: [EnchantType.SWORD],
    description: "A killed enemy sometimes leaves coin behind",
    damageType: [],
    resistanceType: [],
    absorbType: [],
    manaCost: 0,
    cooldown: 0,
    maxLevel: 5,
    price: 72,
    currency: Currency.LEVEL,
  },
  {
    title: "Gallowswing",
    type: [EnchantType.MACE],
    description:
      "Far heavier on an enemy that is off the ground, and it scales with how high they are",
    damageType: [DamageType.PHYSICAL_DMG],
    resistanceType: [ResistanceType.PHYSICAL_RESIST],
    absorbType: [],
    manaCost: 0,
    cooldown: 0,
    maxLevel: 4,
    price: 55,
    currency: Currency.LEVEL,
  },
  {
    title: "Rimefang",
    type: [EnchantType.SWORD, EnchantType.SPEAR],
    description:
      "Slows and chills the target, and bites deeper the longer you keep them cold",
    damageType: [DamageType.MAGICAL_DMG],
    resistanceType: [ResistanceType.MAGICAL_RESIST],
    absorbType: [],
    manaCost: 0,
    cooldown: 0,
    maxLevel: 5,
    price: 60,
    currency: Currency.LEVEL,
  },
  {
    title: "Ledgerburn",
    type: [EnchantType.SWORD, EnchantType.MACE],
    description: "The more health you are missing, the harder you hit",
    damageType: [DamageType.PHYSICAL_DMG],
    resistanceType: [ResistanceType.PHYSICAL_RESIST],
    absorbType: [],
    manaCost: 0,
    cooldown: 0,
    maxLevel: 6,
    price: 66,
    currency: Currency.LEVEL,
  },
  {
    title: "Saltspine",
    type: [EnchantType.SPEAR],
    description:
      "Salts the wound so it will not close, denying the target any healing for a few seconds",
    damageType: [DamageType.PHYSICAL_DMG],
    resistanceType: [ResistanceType.PHYSICAL_RESIST],
    absorbType: [],
    manaCost: 0,
    cooldown: 0,
    maxLevel: 5,
    price: 54,
    currency: Currency.LEVEL,
  },
  {
    title: "Knucklebone",
    type: [EnchantType.MACE],
    description:
      "A gamble on every swing, and the odds are in your favour at every level",
    damageType: [DamageType.PHYSICAL_DMG],
    resistanceType: [ResistanceType.PHYSICAL_RESIST],
    absorbType: [],
    manaCost: 0,
    cooldown: 0,
    maxLevel: 5,
    price: 48,
    currency: Currency.LEVEL,
  },
  {
    title: "Harpoonwake",
    type: [EnchantType.TRIDENT],
    description:
      "Drags a wake back along the flight path, hitting everything standing in the line",
    damageType: [DamageType.PHYSICAL_DMG],
    resistanceType: [ResistanceType.PHYSICAL_RESIST],
    absorbType: [],
    manaCost: 0,
    cooldown: 0,
    maxLevel: 4,
    price: 50,
    currency: Currency.LEVEL,
  },
  {
    title: "Brinelash",
    type: [EnchantType.TRIDENT],
    description:
      "A hit on a soaked target lashes onward to the other soaked enemies near it",
    damageType: [DamageType.PHYSICAL_DMG],
    resistanceType: [ResistanceType.PHYSICAL_RESIST],
    absorbType: [],
    manaCost: 0,
    cooldown: 0,
    maxLevel: 5,
    price: 46,
    currency: Currency.LEVEL,
  },
  {
    title: "Tollshot",
    type: [EnchantType.BOW],
    description:
      "The first arrow into a target nobody has touched yet collects extra",
    damageType: [DamageType.PHYSICAL_DMG],
    resistanceType: [ResistanceType.PHYSICAL_RESIST],
    absorbType: [],
    manaCost: 0,
    cooldown: 0,
    maxLevel: 5,
    price: 58,
    currency: Currency.LEVEL,
  },
  {
    title: "Ravenquill",
    type: [EnchantType.BOW],
    description:
      "Arrows steer toward the nearest hostile while they are in flight",
    damageType: [DamageType.PHYSICAL_DMG],
    resistanceType: [ResistanceType.PHYSICAL_RESIST],
    absorbType: [],
    manaCost: 0,
    cooldown: 0,
    maxLevel: 4,
    price: 64,
    currency: Currency.LEVEL,
  },
  {
    title: "Splintervolley",
    type: [EnchantType.BOW],
    description: "An arrow that lands breaks apart into shards",
    damageType: [DamageType.PHYSICAL_DMG],
    resistanceType: [ResistanceType.PHYSICAL_RESIST],
    absorbType: [],
    manaCost: 0,
    cooldown: 0,
    maxLevel: 5,
    price: 62,
    currency: Currency.LEVEL,
  },
  {
    title: "Voidtithe",
    type: [EnchantType.MAGIC_WAND],
    description:
      "Takes a slice of the target's current health, capped at 12, and a third of it returns to you as mana",
    damageType: [DamageType.MAGICAL_DMG],
    resistanceType: [ResistanceType.MAGICAL_RESIST],
    absorbType: [],
    manaCost: 16,
    cooldown: 42,
    maxLevel: 7,
    price: 110,
    currency: Currency.LEVEL,
  },
  {
    title: "Embertoll",
    type: [EnchantType.MAGIC_WAND],
    description:
      "A ring of fire that expands outward from where you are standing",
    damageType: [DamageType.MAGICAL_DMG],
    resistanceType: [ResistanceType.MAGICAL_RESIST],
    absorbType: [],
    manaCost: 12,
    cooldown: 32,
    maxLevel: 6,
    price: 88,
    currency: Currency.LEVEL,
  },
  {
    title: "Starvein",
    type: [EnchantType.MAGIC_WAND],
    description: "A lance that pierces everything on one straight line",
    damageType: [DamageType.MAGICAL_DMG],
    resistanceType: [ResistanceType.MAGICAL_RESIST],
    absorbType: [],
    manaCost: 20,
    cooldown: 50,
    maxLevel: 8,
    price: 125,
    currency: Currency.LEVEL,
  },
  {
    title: "Glyphwrack",
    type: [EnchantType.MAGIC_WAND],
    description:
      "Sets a sigil that goes off a second and a half later, so you aim it where they are going",
    damageType: [DamageType.MAGICAL_DMG],
    resistanceType: [ResistanceType.MAGICAL_RESIST],
    absorbType: [],
    manaCost: 10,
    cooldown: 26,
    maxLevel: 5,
    price: 78,
    currency: Currency.LEVEL,
  },
  {
    title: "Cofferguard",
    type: [EnchantType.CHESTPLATE],
    description:
      "Spends 1 RACO to soak up to 60% of a heavy hit. An empty wallet is an ordinary chestplate",
    damageType: [],
    resistanceType: [],
    absorbType: [DamageType.PHYSICAL_DMG, DamageType.MAGICAL_DMG],
    manaCost: 0,
    cooldown: 0,
    maxLevel: 5,
    price: 70,
    currency: Currency.LEVEL,
  },
  {
    title: "Vaultskin",
    type: [EnchantType.ARMORS],
    description:
      "Takes a flat amount off every hit instead of a percentage, never dropping a hit below 0.5",
    damageType: [],
    resistanceType: [],
    absorbType: [DamageType.PHYSICAL_DMG, DamageType.MAGICAL_DMG],
    manaCost: 0,
    cooldown: 0,
    maxLevel: 8,
    price: 85,
    currency: Currency.LEVEL,
  },
  {
    title: "Ironvow",
    type: [EnchantType.LEGGINGS],
    description: "Cancels knockback outright and cuts slowness short",
    damageType: [],
    resistanceType: [],
    absorbType: [],
    manaCost: 0,
    cooldown: 0,
    maxLevel: 5,
    price: 52,
    currency: Currency.LEVEL,
  },
  {
    title: "Paleward",
    type: [EnchantType.HELMET],
    description:
      "Blunts magic damage and cuts short the negative statuses you are already carrying",
    damageType: [],
    resistanceType: [],
    absorbType: [DamageType.MAGICAL_DMG],
    manaCost: 0,
    cooldown: 0,
    maxLevel: 5,
    price: 56,
    currency: Currency.LEVEL,
  },
  {
    title: "Tombstride",
    type: [EnchantType.BOOTS],
    description: "The closer you are to dying, the faster you move",
    damageType: [],
    resistanceType: [],
    absorbType: [],
    manaCost: 0,
    cooldown: 0,
    maxLevel: 5,
    price: 60,
    currency: Currency.LEVEL,
  },
  {
    title: "Wardenknot",
    type: [EnchantType.SHIELD],
    description:
      "Blocking winds up a knot, and the fourth blocked hit shoves everything off you",
    damageType: [],
    resistanceType: [],
    absorbType: [],
    manaCost: 0,
    cooldown: 0,
    maxLevel: 5,
    price: 64,
    currency: Currency.LEVEL,
  },
  {
    title: "Coinvein",
    type: [EnchantType.PICKAXE],
    description:
      "Ore sometimes gives up coin as well, 1.5% per level, paid out of circulating supply",
    damageType: [],
    resistanceType: [],
    absorbType: [],
    manaCost: 0,
    cooldown: 0,
    maxLevel: 5,
    price: 45,
    currency: Currency.LEVEL,
  },
  {
    title: "Titherow",
    type: [EnchantType.HOE],
    description:
      "A fully grown harvest sometimes pays, 1% per level, paid out of circulating supply",
    damageType: [],
    resistanceType: [],
    absorbType: [],
    manaCost: 0,
    cooldown: 0,
    maxLevel: 5,
    price: 40,
    currency: Currency.LEVEL,
  },
  {
    title: "Dredgeline",
    type: [EnchantType.FISHING_ROD],
    description:
      "Pulls treasure items and coin up out of the water alongside the catch",
    damageType: [],
    resistanceType: [],
    absorbType: [],
    manaCost: 0,
    cooldown: 0,
    maxLevel: 5,
    price: 38,
    currency: Currency.LEVEL,
  },
];

/**
 * The setup guide section. Aimed at a server owner who has the jar and wants to
 * see what the plugin does before committing to it, which is a different job to
 * the wiki: it stops at "I have seen it work", not "my server is configured".
 *
 * `cmd` renders as a command chip above the body when it is present.
 */
export const SetupSteps = [
  {
    n: "1",
    title: "DROP THE JAR IN",
    body: "Stop the server, put CustomEnchantments3.jar in the plugins folder, start it again. The lite build is CustomEnchantments3-lite.jar and installs the same way. Nothing else is required: no Vault, no permissions plugin, no database. The plugins/CustomEnchantments3 folder and everything under PluginData is written on that first start.",
  },
  {
    n: "2",
    title: "CHECK THE BANNER",
    body: "A few seconds after boot the plugin prints its banner, and the License line on it says PREMIUM or LITE. The two jars look identical in a plugins folder apart from the file name, so that line is how you know which one is actually running. The count of registered enchantment books is logged just above it.",
  },
  {
    n: "3",
    title: "GIVE YOURSELF ADMIN",
    cmd: "EnableAuthorizationYML",
    body: "It ships as false, which means being OP is enough and you can start testing straight away. That is the setting that makes the plugin workable on a host where OP is all you have. Set it to true before you open the server and OP stops being enough: only the names listed in PluginData/Authorization.yml can run the admin commands. Bedrock names through Geyser or Floodgate keep their leading dot.",
  },
  {
    n: "4",
    title: "MAKE A TEST CHARACTER",
    cmd: "/ce ___test___",
    body: "Grants the max skill level of 200 and opens the skill tree on the spot, so the classes, the passives and the enchantments can all be looked at without playing to 200 first. The test commands below are the rest of that toolkit.",
  },
  {
    n: "5",
    title: "BUILD THE REAL THINGS",
    cmd: "/ce shop add [mobType] [shopType] [shopName]",
    body: "Shops, quests and loot plots are made from in game commands, and they are the same commands on a live server: /ce quest add walks through a quest, /ce settings LootingPlot generate places a plot, and /ce settings LootingPlot list shows the ones that exist.",
  },
  {
    n: "6",
    title: "EDIT, RELOAD, REPEAT",
    cmd: "/ce reload",
    body: "Every price, limit and rate lives in config.yml. Change it, run the reload, and the file is read again without a restart. /ce info shows what is loaded right now. On the lite build shop prices come from the copy inside the jar rather than yours, and the reload says so instead of leaving you guessing.",
  },
];

/**
 * The op only test commands. They are in the command table too, but nobody
 * evaluating the plugin reads a 24 row table looking for them, and they are the
 * fastest way to see what the plugin actually does.
 */
export const TestCommands = [
  {
    cmd: "/ce ___test___",
    accent: "lime",
    icon: "fa-solid fa-bolt",
    body: "Max skill level, 200, and the skill tree opens straight away. Classes unlock at level 10, so this is also how you see the class paths without grinding to them.",
  },
  {
    cmd: "/ce ___treasure___",
    accent: "amber",
    icon: "fa-solid fa-gem",
    body: "Puts one of every treasure in the pool into your inventory. On the lite build the pool is common and uncommon only, so a short list here is the edition, not a fault.",
  },
  {
    cmd: "/ce ___ceItem___",
    accent: "purple",
    icon: "fa-solid fa-cube",
    body: "Hands you a single random loot item, the same roll a loot chest makes. Run it a few times to see the spread.",
  },
  {
    cmd: "/ce ___lootplot___",
    accent: "rose",
    icon: "fa-solid fa-city",
    body: "Builds a looting plot where you stand instead of waiting for one to generate. It warns you before it runs: the structure is built on the main thread and can stall a small server for a moment. Test box only.",
  },
  {
    cmd: "/ce ___itemData___",
    accent: "sky",
    icon: "fa-solid fa-magnifying-glass",
    body: "Prints the enchantment data stored on the item in your main hand. This is the one to reach for when an item is not behaving the way you expect it to.",
  },
  {
    cmd: "/ce ___reset___",
    accent: "slate",
    icon: "fa-solid fa-rotate-left",
    body: "Puts your own account back to skill level 0 and empties its RACO. Run it on every account you tested with before the server opens.",
  },
];
